package calibrate

// Archetypes defines the 3 domain archetypes used for schema generation.
// Each domain is a heavyweight merged schema (15-35 tables) combining multiple
// concern layers (business logic + RBAC + IoT/documents + supply chain) to produce
// realistic multi-layer query patterns that stress all scoring rules.
func Archetypes() []Domain {
	return []Domain{
		cashAccountingDomain(),
		accrualAccountingDomain(),
		healthcareDomain(),
	}
}

// cashAccountingDomain models a comprehensive cash-basis accounting system for a CPA
// firm managing multiple client businesses. 15 tables with soft-delete markers, JSONB
// metadata, temporal validity (fiscal periods, effective dates), and deep join chains
// for financial reporting queries. Revenue recognized when cash received, expenses when paid.
func cashAccountingDomain() Domain {
	return Domain{
		Name:        "cash_accounting",
		Description: "Full cash-basis CPA system with 15 tables, soft-delete, fiscal periods, payroll",
		Tables: []TableDef{
			{Name: "businesses", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "name", Type: "VARCHAR(200)", NotNull: true},
				{Name: "ein", Type: "VARCHAR(12)", NotNull: true},
				{Name: "entity_type", Type: "VARCHAR(20)", NotNull: true},
				{Name: "industry", Type: "VARCHAR(50)"},
				{Name: "fiscal_year_end", Type: "DATE", NotNull: true},
				{Name: "formed_date", Type: "DATE", NotNull: true},
				{Name: "address", Type: "TEXT"},
				{Name: "phone", Type: "VARCHAR(20)"},
				{Name: "is_active", Type: "BOOLEAN", NotNull: true, Default: "true"},
				{Name: "metadata", Type: "JSONB"},
				{Name: "created_at", Type: "TIMESTAMPTZ", NotNull: true, Default: "now()"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "customers", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "business_id", Type: "INT", NotNull: true},
				{Name: "name", Type: "VARCHAR(200)", NotNull: true},
				{Name: "email", Type: "VARCHAR(255)"},
				{Name: "phone", Type: "VARCHAR(20)"},
				{Name: "tax_id", Type: "VARCHAR(20)"},
				{Name: "payment_terms", Type: "VARCHAR(20)", NotNull: true, Default: "'net_30'"},
				{Name: "credit_limit", Type: "NUMERIC(14,2)"},
				{Name: "created_at", Type: "TIMESTAMPTZ", NotNull: true, Default: "now()"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "vendors", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "business_id", Type: "INT", NotNull: true},
				{Name: "name", Type: "VARCHAR(200)", NotNull: true},
				{Name: "email", Type: "VARCHAR(255)"},
				{Name: "tax_id", Type: "VARCHAR(20)"},
				{Name: "vendor_type", Type: "VARCHAR(30)", NotNull: true},
				{Name: "is_1099_eligible", Type: "BOOLEAN", NotNull: true, Default: "false"},
				{Name: "payment_terms", Type: "VARCHAR(20)", NotNull: true, Default: "'net_30'"},
				{Name: "created_at", Type: "TIMESTAMPTZ", NotNull: true, Default: "now()"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "chart_of_accounts", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "business_id", Type: "INT", NotNull: true},
				{Name: "account_code", Type: "VARCHAR(20)", NotNull: true},
				{Name: "account_name", Type: "VARCHAR(100)", NotNull: true},
				{Name: "account_type", Type: "VARCHAR(20)", NotNull: true},
				{Name: "normal_balance", Type: "VARCHAR(10)", NotNull: true},
				{Name: "parent_account_id", Type: "INT"},
				{Name: "is_active", Type: "BOOLEAN", NotNull: true, Default: "true"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "fiscal_periods", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "business_id", Type: "INT", NotNull: true},
				{Name: "period_name", Type: "VARCHAR(30)", NotNull: true},
				{Name: "start_date", Type: "DATE", NotNull: true},
				{Name: "end_date", Type: "DATE", NotNull: true},
				{Name: "status", Type: "VARCHAR(20)", NotNull: true, Default: "'open'"},
				{Name: "closed_at", Type: "TIMESTAMPTZ"},
				{Name: "closed_by", Type: "INT"},
			}},
			{Name: "bank_accounts", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "business_id", Type: "INT", NotNull: true},
				{Name: "account_name", Type: "VARCHAR(100)", NotNull: true},
				{Name: "institution", Type: "VARCHAR(100)", NotNull: true},
				{Name: "routing_number", Type: "VARCHAR(12)"},
				{Name: "account_number", Type: "VARCHAR(20)"},
				{Name: "current_balance", Type: "NUMERIC(14,2)", NotNull: true, Default: "0"},
				{Name: "opened_date", Type: "DATE", NotNull: true},
				{Name: "closed_date", Type: "DATE"},
				{Name: "is_active", Type: "BOOLEAN", NotNull: true, Default: "true"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "cash_receipts", Columns: []ColumnDef{
				{Name: "id", Type: "BIGSERIAL", IsSerial: true},
				{Name: "business_id", Type: "INT", NotNull: true},
				{Name: "customer_id", Type: "INT"},
				{Name: "bank_account_id", Type: "INT", NotNull: true},
				{Name: "account_id", Type: "INT", NotNull: true},
				{Name: "fiscal_period_id", Type: "INT", NotNull: true},
				{Name: "receipt_date", Type: "DATE", NotNull: true},
				{Name: "amount", Type: "NUMERIC(14,2)", NotNull: true},
				{Name: "reference_number", Type: "VARCHAR(50)"},
				{Name: "memo", Type: "TEXT"},
				{Name: "payment_method", Type: "VARCHAR(20)"},
				{Name: "deposited_at", Type: "TIMESTAMPTZ"},
				{Name: "metadata", Type: "JSONB"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "cash_disbursements", Columns: []ColumnDef{
				{Name: "id", Type: "BIGSERIAL", IsSerial: true},
				{Name: "business_id", Type: "INT", NotNull: true},
				{Name: "vendor_id", Type: "INT"},
				{Name: "bank_account_id", Type: "INT", NotNull: true},
				{Name: "account_id", Type: "INT", NotNull: true},
				{Name: "fiscal_period_id", Type: "INT", NotNull: true},
				{Name: "payment_date", Type: "DATE", NotNull: true},
				{Name: "amount", Type: "NUMERIC(14,2)", NotNull: true},
				{Name: "check_number", Type: "VARCHAR(20)"},
				{Name: "memo", Type: "TEXT"},
				{Name: "payment_method", Type: "VARCHAR(20)"},
				{Name: "cleared_at", Type: "TIMESTAMPTZ"},
				{Name: "metadata", Type: "JSONB"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "fixed_assets", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "business_id", Type: "INT", NotNull: true},
				{Name: "asset_name", Type: "VARCHAR(200)", NotNull: true},
				{Name: "asset_class", Type: "VARCHAR(50)", NotNull: true},
				{Name: "purchase_date", Type: "DATE", NotNull: true},
				{Name: "cost_basis", Type: "NUMERIC(14,2)", NotNull: true},
				{Name: "salvage_value", Type: "NUMERIC(14,2)", NotNull: true, Default: "0"},
				{Name: "useful_life_months", Type: "INT", NotNull: true},
				{Name: "depreciation_method", Type: "VARCHAR(20)", NotNull: true, Default: "'straight_line'"},
				{Name: "accumulated_depreciation", Type: "NUMERIC(14,2)", NotNull: true, Default: "0"},
				{Name: "disposed_date", Type: "DATE"},
				{Name: "disposal_amount", Type: "NUMERIC(14,2)"},
				{Name: "account_id", Type: "INT", NotNull: true},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "depreciation_entries", Columns: []ColumnDef{
				{Name: "id", Type: "BIGSERIAL", IsSerial: true},
				{Name: "fixed_asset_id", Type: "INT", NotNull: true},
				{Name: "fiscal_period_id", Type: "INT", NotNull: true},
				{Name: "amount", Type: "NUMERIC(14,2)", NotNull: true},
				{Name: "entry_date", Type: "DATE", NotNull: true},
				{Name: "cumulative_total", Type: "NUMERIC(14,2)", NotNull: true},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "payroll_runs", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "business_id", Type: "INT", NotNull: true},
				{Name: "fiscal_period_id", Type: "INT", NotNull: true},
				{Name: "pay_date", Type: "DATE", NotNull: true},
				{Name: "period_start", Type: "DATE", NotNull: true},
				{Name: "period_end", Type: "DATE", NotNull: true},
				{Name: "total_gross", Type: "NUMERIC(14,2)", NotNull: true},
				{Name: "total_withholdings", Type: "NUMERIC(14,2)", NotNull: true},
				{Name: "total_employer_taxes", Type: "NUMERIC(14,2)", NotNull: true},
				{Name: "total_net", Type: "NUMERIC(14,2)", NotNull: true},
				{Name: "status", Type: "VARCHAR(20)", NotNull: true, Default: "'draft'"},
				{Name: "approved_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "payroll_items", Columns: []ColumnDef{
				{Name: "id", Type: "BIGSERIAL", IsSerial: true},
				{Name: "payroll_run_id", Type: "INT", NotNull: true},
				{Name: "employee_name", Type: "VARCHAR(200)", NotNull: true},
				{Name: "gross_pay", Type: "NUMERIC(10,2)", NotNull: true},
				{Name: "federal_tax", Type: "NUMERIC(10,2)", NotNull: true},
				{Name: "state_tax", Type: "NUMERIC(10,2)", NotNull: true},
				{Name: "social_security", Type: "NUMERIC(10,2)", NotNull: true},
				{Name: "medicare", Type: "NUMERIC(10,2)", NotNull: true},
				{Name: "other_deductions", Type: "NUMERIC(10,2)", NotNull: true, Default: "0"},
				{Name: "net_pay", Type: "NUMERIC(10,2)", NotNull: true},
				{Name: "pay_type", Type: "VARCHAR(20)", NotNull: true},
				{Name: "hours_worked", Type: "NUMERIC(6,2)"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "bank_reconciliations", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "bank_account_id", Type: "INT", NotNull: true},
				{Name: "fiscal_period_id", Type: "INT", NotNull: true},
				{Name: "statement_date", Type: "DATE", NotNull: true},
				{Name: "statement_balance", Type: "NUMERIC(14,2)", NotNull: true},
				{Name: "book_balance", Type: "NUMERIC(14,2)", NotNull: true},
				{Name: "difference", Type: "NUMERIC(14,2)", NotNull: true},
				{Name: "status", Type: "VARCHAR(20)", NotNull: true, Default: "'pending'"},
				{Name: "reconciled_at", Type: "TIMESTAMPTZ"},
				{Name: "reconciled_by", Type: "VARCHAR(100)"},
				{Name: "notes", Type: "TEXT"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "tax_payments", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "business_id", Type: "INT", NotNull: true},
				{Name: "fiscal_period_id", Type: "INT", NotNull: true},
				{Name: "tax_type", Type: "VARCHAR(30)", NotNull: true},
				{Name: "tax_authority", Type: "VARCHAR(50)", NotNull: true},
				{Name: "amount", Type: "NUMERIC(14,2)", NotNull: true},
				{Name: "due_date", Type: "DATE", NotNull: true},
				{Name: "paid_date", Type: "DATE"},
				{Name: "confirmation_number", Type: "VARCHAR(50)"},
				{Name: "status", Type: "VARCHAR(20)", NotNull: true, Default: "'pending'"},
				{Name: "penalty_amount", Type: "NUMERIC(10,2)"},
				{Name: "interest_amount", Type: "NUMERIC(10,2)"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "form_1099s", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "business_id", Type: "INT", NotNull: true},
				{Name: "vendor_id", Type: "INT", NotNull: true},
				{Name: "tax_year", Type: "INT", NotNull: true},
				{Name: "form_type", Type: "VARCHAR(10)", NotNull: true, Default: "'NEC'"},
				{Name: "total_paid", Type: "NUMERIC(14,2)", NotNull: true},
				{Name: "reported_amount", Type: "NUMERIC(14,2)", NotNull: true},
				{Name: "filed_at", Type: "TIMESTAMPTZ"},
				{Name: "corrected", Type: "BOOLEAN", NotNull: true, Default: "false"},
				{Name: "metadata", Type: "JSONB"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
		},
		Indexes: []IndexDef{
			{Name: "idx_ca_biz_ein", Table: "businesses", Columns: []string{"ein"}, Unique: true},
			{Name: "idx_ca_biz_entity_type", Table: "businesses", Columns: []string{"entity_type"}},
			{Name: "idx_ca_biz_deleted", Table: "businesses", Columns: []string{"deleted_at"}},
			{Name: "idx_ca_cust_business", Table: "customers", Columns: []string{"business_id"}},
			{Name: "idx_ca_cust_email", Table: "customers", Columns: []string{"email"}},
			{Name: "idx_ca_cust_deleted", Table: "customers", Columns: []string{"deleted_at"}},
			{Name: "idx_ca_vend_business", Table: "vendors", Columns: []string{"business_id"}},
			{Name: "idx_ca_vend_deleted", Table: "vendors", Columns: []string{"deleted_at"}},
			{Name: "idx_ca_coa_business", Table: "chart_of_accounts", Columns: []string{"business_id"}},
			{Name: "idx_ca_coa_code", Table: "chart_of_accounts", Columns: []string{"business_id", "account_code"}, Unique: true},
			{Name: "idx_ca_coa_type", Table: "chart_of_accounts", Columns: []string{"account_type"}},
			{Name: "idx_ca_coa_parent", Table: "chart_of_accounts", Columns: []string{"parent_account_id"}},
			{Name: "idx_ca_fp_business", Table: "fiscal_periods", Columns: []string{"business_id"}},
			{Name: "idx_ca_fp_dates", Table: "fiscal_periods", Columns: []string{"start_date", "end_date"}},
			{Name: "idx_ca_fp_status", Table: "fiscal_periods", Columns: []string{"status"}},
			{Name: "idx_ca_bank_business", Table: "bank_accounts", Columns: []string{"business_id"}},
			{Name: "idx_ca_rcpt_business", Table: "cash_receipts", Columns: []string{"business_id"}},
			{Name: "idx_ca_rcpt_customer", Table: "cash_receipts", Columns: []string{"customer_id"}},
			{Name: "idx_ca_rcpt_bank", Table: "cash_receipts", Columns: []string{"bank_account_id"}},
			{Name: "idx_ca_rcpt_account", Table: "cash_receipts", Columns: []string{"account_id"}},
			{Name: "idx_ca_rcpt_period", Table: "cash_receipts", Columns: []string{"fiscal_period_id"}},
			{Name: "idx_ca_rcpt_date", Table: "cash_receipts", Columns: []string{"receipt_date"}},
			{Name: "idx_ca_rcpt_deleted", Table: "cash_receipts", Columns: []string{"deleted_at"}},
			{Name: "idx_ca_disb_business", Table: "cash_disbursements", Columns: []string{"business_id"}},
			{Name: "idx_ca_disb_vendor", Table: "cash_disbursements", Columns: []string{"vendor_id"}},
			{Name: "idx_ca_disb_bank", Table: "cash_disbursements", Columns: []string{"bank_account_id"}},
			{Name: "idx_ca_disb_account", Table: "cash_disbursements", Columns: []string{"account_id"}},
			{Name: "idx_ca_disb_period", Table: "cash_disbursements", Columns: []string{"fiscal_period_id"}},
			{Name: "idx_ca_disb_date", Table: "cash_disbursements", Columns: []string{"payment_date"}},
			{Name: "idx_ca_disb_deleted", Table: "cash_disbursements", Columns: []string{"deleted_at"}},
			{Name: "idx_ca_fa_business", Table: "fixed_assets", Columns: []string{"business_id"}},
			{Name: "idx_ca_fa_class", Table: "fixed_assets", Columns: []string{"asset_class"}},
			{Name: "idx_ca_fa_account", Table: "fixed_assets", Columns: []string{"account_id"}},
			{Name: "idx_ca_fa_purchase", Table: "fixed_assets", Columns: []string{"purchase_date"}},
			{Name: "idx_ca_dep_asset", Table: "depreciation_entries", Columns: []string{"fixed_asset_id"}},
			{Name: "idx_ca_dep_period", Table: "depreciation_entries", Columns: []string{"fiscal_period_id"}},
			{Name: "idx_ca_pr_business", Table: "payroll_runs", Columns: []string{"business_id"}},
			{Name: "idx_ca_pr_period", Table: "payroll_runs", Columns: []string{"fiscal_period_id"}},
			{Name: "idx_ca_pr_date", Table: "payroll_runs", Columns: []string{"pay_date"}},
			{Name: "idx_ca_pr_status", Table: "payroll_runs", Columns: []string{"status"}},
			{Name: "idx_ca_pi_run", Table: "payroll_items", Columns: []string{"payroll_run_id"}},
			{Name: "idx_ca_pi_type", Table: "payroll_items", Columns: []string{"pay_type"}},
			{Name: "idx_ca_br_bank", Table: "bank_reconciliations", Columns: []string{"bank_account_id"}},
			{Name: "idx_ca_br_period", Table: "bank_reconciliations", Columns: []string{"fiscal_period_id"}},
			{Name: "idx_ca_br_status", Table: "bank_reconciliations", Columns: []string{"status"}},
			{Name: "idx_ca_tp_business", Table: "tax_payments", Columns: []string{"business_id"}},
			{Name: "idx_ca_tp_period", Table: "tax_payments", Columns: []string{"fiscal_period_id"}},
			{Name: "idx_ca_tp_type", Table: "tax_payments", Columns: []string{"tax_type"}},
			{Name: "idx_ca_tp_due", Table: "tax_payments", Columns: []string{"due_date"}},
			{Name: "idx_ca_tp_status", Table: "tax_payments", Columns: []string{"status"}},
			{Name: "idx_ca_1099_business", Table: "form_1099s", Columns: []string{"business_id"}},
			{Name: "idx_ca_1099_vendor", Table: "form_1099s", Columns: []string{"vendor_id"}},
			{Name: "idx_ca_1099_year", Table: "form_1099s", Columns: []string{"tax_year"}},
			{Name: "idx_ca_1099_biz_year", Table: "form_1099s", Columns: []string{"business_id", "vendor_id", "tax_year"}, Unique: true},
		},
		ForeignKeys: []FKDef{
			{Name: "fk_ca_cust_biz", Table: "customers", Column: "business_id", RefTable: "businesses", RefColumn: "id"},
			{Name: "fk_ca_vend_biz", Table: "vendors", Column: "business_id", RefTable: "businesses", RefColumn: "id"},
			{Name: "fk_ca_coa_biz", Table: "chart_of_accounts", Column: "business_id", RefTable: "businesses", RefColumn: "id"},
			{Name: "fk_ca_coa_parent", Table: "chart_of_accounts", Column: "parent_account_id", RefTable: "chart_of_accounts", RefColumn: "id"},
			{Name: "fk_ca_fp_biz", Table: "fiscal_periods", Column: "business_id", RefTable: "businesses", RefColumn: "id"},
			{Name: "fk_ca_bank_biz", Table: "bank_accounts", Column: "business_id", RefTable: "businesses", RefColumn: "id"},
			{Name: "fk_ca_rcpt_biz", Table: "cash_receipts", Column: "business_id", RefTable: "businesses", RefColumn: "id"},
			{Name: "fk_ca_rcpt_cust", Table: "cash_receipts", Column: "customer_id", RefTable: "customers", RefColumn: "id"},
			{Name: "fk_ca_rcpt_bank", Table: "cash_receipts", Column: "bank_account_id", RefTable: "bank_accounts", RefColumn: "id"},
			{Name: "fk_ca_rcpt_acct", Table: "cash_receipts", Column: "account_id", RefTable: "chart_of_accounts", RefColumn: "id"},
			{Name: "fk_ca_rcpt_period", Table: "cash_receipts", Column: "fiscal_period_id", RefTable: "fiscal_periods", RefColumn: "id"},
			{Name: "fk_ca_disb_biz", Table: "cash_disbursements", Column: "business_id", RefTable: "businesses", RefColumn: "id"},
			{Name: "fk_ca_disb_vend", Table: "cash_disbursements", Column: "vendor_id", RefTable: "vendors", RefColumn: "id"},
			{Name: "fk_ca_disb_bank", Table: "cash_disbursements", Column: "bank_account_id", RefTable: "bank_accounts", RefColumn: "id"},
			{Name: "fk_ca_disb_acct", Table: "cash_disbursements", Column: "account_id", RefTable: "chart_of_accounts", RefColumn: "id"},
			{Name: "fk_ca_disb_period", Table: "cash_disbursements", Column: "fiscal_period_id", RefTable: "fiscal_periods", RefColumn: "id"},
			{Name: "fk_ca_fa_biz", Table: "fixed_assets", Column: "business_id", RefTable: "businesses", RefColumn: "id"},
			{Name: "fk_ca_fa_acct", Table: "fixed_assets", Column: "account_id", RefTable: "chart_of_accounts", RefColumn: "id"},
			{Name: "fk_ca_dep_asset", Table: "depreciation_entries", Column: "fixed_asset_id", RefTable: "fixed_assets", RefColumn: "id"},
			{Name: "fk_ca_dep_period", Table: "depreciation_entries", Column: "fiscal_period_id", RefTable: "fiscal_periods", RefColumn: "id"},
			{Name: "fk_ca_pr_biz", Table: "payroll_runs", Column: "business_id", RefTable: "businesses", RefColumn: "id"},
			{Name: "fk_ca_pr_period", Table: "payroll_runs", Column: "fiscal_period_id", RefTable: "fiscal_periods", RefColumn: "id"},
			{Name: "fk_ca_pi_run", Table: "payroll_items", Column: "payroll_run_id", RefTable: "payroll_runs", RefColumn: "id"},
			{Name: "fk_ca_br_bank", Table: "bank_reconciliations", Column: "bank_account_id", RefTable: "bank_accounts", RefColumn: "id"},
			{Name: "fk_ca_br_period", Table: "bank_reconciliations", Column: "fiscal_period_id", RefTable: "fiscal_periods", RefColumn: "id"},
			{Name: "fk_ca_tp_biz", Table: "tax_payments", Column: "business_id", RefTable: "businesses", RefColumn: "id"},
			{Name: "fk_ca_tp_period", Table: "tax_payments", Column: "fiscal_period_id", RefTable: "fiscal_periods", RefColumn: "id"},
			{Name: "fk_ca_1099_biz", Table: "form_1099s", Column: "business_id", RefTable: "businesses", RefColumn: "id"},
			{Name: "fk_ca_1099_vend", Table: "form_1099s", Column: "vendor_id", RefTable: "vendors", RefColumn: "id"},
		},
	}
}


func accrualAccountingDomain() Domain {
	return Domain{
		Name:        "accrual_accounting",
		Description: "Full accrual-basis GL with 29 tables: 16 core accounting, RBAC (users/roles/permissions), document management with versioning and annotations, regulatory filings, audit trail",
		Tables: []TableDef{
			// ──────────────────────────────────────────────
			// Original 16 accrual accounting tables
			// ──────────────────────────────────────────────
			{Name: "businesses", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "name", Type: "VARCHAR(200)", NotNull: true},
				{Name: "ein", Type: "VARCHAR(12)", NotNull: true},
				{Name: "entity_type", Type: "VARCHAR(20)", NotNull: true},
				{Name: "industry", Type: "VARCHAR(50)"},
				{Name: "fiscal_year_end", Type: "DATE", NotNull: true},
				{Name: "incorporation_date", Type: "DATE", NotNull: true},
				{Name: "is_active", Type: "BOOLEAN", NotNull: true, Default: "true"},
				{Name: "metadata", Type: "JSONB"},
				{Name: "created_by", Type: "INT"},
				{Name: "created_at", Type: "TIMESTAMPTZ", NotNull: true, Default: "now()"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "customers", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "business_id", Type: "INT", NotNull: true},
				{Name: "name", Type: "VARCHAR(200)", NotNull: true},
				{Name: "email", Type: "VARCHAR(255)"},
				{Name: "phone", Type: "VARCHAR(20)"},
				{Name: "billing_address", Type: "TEXT"},
				{Name: "payment_terms", Type: "VARCHAR(20)", NotNull: true, Default: "'net_30'"},
				{Name: "credit_limit", Type: "NUMERIC(14,2)"},
				{Name: "current_balance", Type: "NUMERIC(14,2)", NotNull: true, Default: "0"},
				{Name: "created_at", Type: "TIMESTAMPTZ", NotNull: true, Default: "now()"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "vendors", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "business_id", Type: "INT", NotNull: true},
				{Name: "name", Type: "VARCHAR(200)", NotNull: true},
				{Name: "email", Type: "VARCHAR(255)"},
				{Name: "payment_terms", Type: "VARCHAR(20)", NotNull: true, Default: "'net_30'"},
				{Name: "vendor_type", Type: "VARCHAR(30)", NotNull: true},
				{Name: "is_1099_eligible", Type: "BOOLEAN", NotNull: true, Default: "false"},
				{Name: "current_balance", Type: "NUMERIC(14,2)", NotNull: true, Default: "0"},
				{Name: "created_at", Type: "TIMESTAMPTZ", NotNull: true, Default: "now()"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "chart_of_accounts", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "business_id", Type: "INT", NotNull: true},
				{Name: "account_code", Type: "VARCHAR(20)", NotNull: true},
				{Name: "account_name", Type: "VARCHAR(100)", NotNull: true},
				{Name: "account_type", Type: "VARCHAR(20)", NotNull: true},
				{Name: "normal_balance", Type: "VARCHAR(10)", NotNull: true},
				{Name: "parent_account_id", Type: "INT"},
				{Name: "is_active", Type: "BOOLEAN", NotNull: true, Default: "true"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "fiscal_periods", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "business_id", Type: "INT", NotNull: true},
				{Name: "period_name", Type: "VARCHAR(30)", NotNull: true},
				{Name: "start_date", Type: "DATE", NotNull: true},
				{Name: "end_date", Type: "DATE", NotNull: true},
				{Name: "status", Type: "VARCHAR(20)", NotNull: true, Default: "'open'"},
				{Name: "closed_at", Type: "TIMESTAMPTZ"},
				{Name: "closed_by", Type: "INT"},
			}},
			{Name: "invoices", Columns: []ColumnDef{
				{Name: "id", Type: "BIGSERIAL", IsSerial: true},
				{Name: "business_id", Type: "INT", NotNull: true},
				{Name: "customer_id", Type: "INT", NotNull: true},
				{Name: "fiscal_period_id", Type: "INT", NotNull: true},
				{Name: "invoice_number", Type: "VARCHAR(20)", NotNull: true},
				{Name: "invoice_date", Type: "DATE", NotNull: true},
				{Name: "due_date", Type: "DATE", NotNull: true},
				{Name: "subtotal", Type: "NUMERIC(14,2)", NotNull: true},
				{Name: "tax_amount", Type: "NUMERIC(14,2)", NotNull: true, Default: "0"},
				{Name: "total_amount", Type: "NUMERIC(14,2)", NotNull: true},
				{Name: "amount_paid", Type: "NUMERIC(14,2)", NotNull: true, Default: "0"},
				{Name: "status", Type: "VARCHAR(20)", NotNull: true, Default: "'issued'"},
				{Name: "line_items", Type: "JSONB"},
				{Name: "created_by", Type: "INT"},
				{Name: "created_at", Type: "TIMESTAMPTZ", NotNull: true, Default: "now()"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "bills", Columns: []ColumnDef{
				{Name: "id", Type: "BIGSERIAL", IsSerial: true},
				{Name: "business_id", Type: "INT", NotNull: true},
				{Name: "vendor_id", Type: "INT", NotNull: true},
				{Name: "fiscal_period_id", Type: "INT", NotNull: true},
				{Name: "bill_number", Type: "VARCHAR(20)", NotNull: true},
				{Name: "bill_date", Type: "DATE", NotNull: true},
				{Name: "due_date", Type: "DATE", NotNull: true},
				{Name: "subtotal", Type: "NUMERIC(14,2)", NotNull: true},
				{Name: "tax_amount", Type: "NUMERIC(14,2)", NotNull: true, Default: "0"},
				{Name: "total_amount", Type: "NUMERIC(14,2)", NotNull: true},
				{Name: "amount_paid", Type: "NUMERIC(14,2)", NotNull: true, Default: "0"},
				{Name: "status", Type: "VARCHAR(20)", NotNull: true, Default: "'received'"},
				{Name: "line_items", Type: "JSONB"},
				{Name: "created_by", Type: "INT"},
				{Name: "created_at", Type: "TIMESTAMPTZ", NotNull: true, Default: "now()"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "payments_received", Columns: []ColumnDef{
				{Name: "id", Type: "BIGSERIAL", IsSerial: true},
				{Name: "business_id", Type: "INT", NotNull: true},
				{Name: "customer_id", Type: "INT", NotNull: true},
				{Name: "invoice_id", Type: "INT"},
				{Name: "fiscal_period_id", Type: "INT", NotNull: true},
				{Name: "payment_date", Type: "DATE", NotNull: true},
				{Name: "amount", Type: "NUMERIC(14,2)", NotNull: true},
				{Name: "payment_method", Type: "VARCHAR(20)", NotNull: true},
				{Name: "reference_number", Type: "VARCHAR(50)"},
				{Name: "deposit_account_id", Type: "INT", NotNull: true},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "payments_made", Columns: []ColumnDef{
				{Name: "id", Type: "BIGSERIAL", IsSerial: true},
				{Name: "business_id", Type: "INT", NotNull: true},
				{Name: "vendor_id", Type: "INT", NotNull: true},
				{Name: "bill_id", Type: "INT"},
				{Name: "fiscal_period_id", Type: "INT", NotNull: true},
				{Name: "payment_date", Type: "DATE", NotNull: true},
				{Name: "amount", Type: "NUMERIC(14,2)", NotNull: true},
				{Name: "payment_method", Type: "VARCHAR(20)", NotNull: true},
				{Name: "check_number", Type: "VARCHAR(20)"},
				{Name: "bank_account_id", Type: "INT", NotNull: true},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "journal_entries", Columns: []ColumnDef{
				{Name: "id", Type: "BIGSERIAL", IsSerial: true},
				{Name: "business_id", Type: "INT", NotNull: true},
				{Name: "fiscal_period_id", Type: "INT", NotNull: true},
				{Name: "entry_date", Type: "DATE", NotNull: true},
				{Name: "description", Type: "TEXT", NotNull: true},
				{Name: "reference_number", Type: "VARCHAR(50)"},
				{Name: "entry_type", Type: "VARCHAR(20)", NotNull: true, Default: "'standard'"},
				{Name: "source_type", Type: "VARCHAR(20)"},
				{Name: "source_id", Type: "INT"},
				{Name: "is_adjusting", Type: "BOOLEAN", NotNull: true, Default: "false"},
				{Name: "is_reversing", Type: "BOOLEAN", NotNull: true, Default: "false"},
				{Name: "posted_at", Type: "TIMESTAMPTZ"},
				{Name: "created_by", Type: "INT"},
				{Name: "created_at", Type: "TIMESTAMPTZ", NotNull: true, Default: "now()"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "journal_lines", Columns: []ColumnDef{
				{Name: "id", Type: "BIGSERIAL", IsSerial: true},
				{Name: "journal_entry_id", Type: "INT", NotNull: true},
				{Name: "account_id", Type: "INT", NotNull: true},
				{Name: "debit_amount", Type: "NUMERIC(14,2)", NotNull: true, Default: "0"},
				{Name: "credit_amount", Type: "NUMERIC(14,2)", NotNull: true, Default: "0"},
				{Name: "memo", Type: "TEXT"},
				{Name: "entity_type", Type: "VARCHAR(20)"},
				{Name: "entity_id", Type: "INT"},
			}},
			{Name: "ar_aging", Columns: []ColumnDef{
				{Name: "id", Type: "BIGSERIAL", IsSerial: true},
				{Name: "business_id", Type: "INT", NotNull: true},
				{Name: "customer_id", Type: "INT", NotNull: true},
				{Name: "invoice_id", Type: "INT", NotNull: true},
				{Name: "as_of_date", Type: "DATE", NotNull: true},
				{Name: "total_due", Type: "NUMERIC(14,2)", NotNull: true},
				{Name: "current_amount", Type: "NUMERIC(14,2)", NotNull: true, Default: "0"},
				{Name: "days_30", Type: "NUMERIC(14,2)", NotNull: true, Default: "0"},
				{Name: "days_60", Type: "NUMERIC(14,2)", NotNull: true, Default: "0"},
				{Name: "days_90", Type: "NUMERIC(14,2)", NotNull: true, Default: "0"},
				{Name: "days_over_90", Type: "NUMERIC(14,2)", NotNull: true, Default: "0"},
			}},
			{Name: "ap_aging", Columns: []ColumnDef{
				{Name: "id", Type: "BIGSERIAL", IsSerial: true},
				{Name: "business_id", Type: "INT", NotNull: true},
				{Name: "vendor_id", Type: "INT", NotNull: true},
				{Name: "bill_id", Type: "INT", NotNull: true},
				{Name: "as_of_date", Type: "DATE", NotNull: true},
				{Name: "total_due", Type: "NUMERIC(14,2)", NotNull: true},
				{Name: "current_amount", Type: "NUMERIC(14,2)", NotNull: true, Default: "0"},
				{Name: "days_30", Type: "NUMERIC(14,2)", NotNull: true, Default: "0"},
				{Name: "days_60", Type: "NUMERIC(14,2)", NotNull: true, Default: "0"},
				{Name: "days_90", Type: "NUMERIC(14,2)", NotNull: true, Default: "0"},
				{Name: "days_over_90", Type: "NUMERIC(14,2)", NotNull: true, Default: "0"},
			}},
			{Name: "budgets", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "business_id", Type: "INT", NotNull: true},
				{Name: "account_id", Type: "INT", NotNull: true},
				{Name: "fiscal_period_id", Type: "INT", NotNull: true},
				{Name: "budgeted_amount", Type: "NUMERIC(14,2)", NotNull: true},
				{Name: "actual_amount", Type: "NUMERIC(14,2)"},
				{Name: "variance", Type: "NUMERIC(14,2)"},
				{Name: "notes", Type: "TEXT"},
				{Name: "approved_at", Type: "TIMESTAMPTZ"},
				{Name: "approved_by", Type: "VARCHAR(100)"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "audit_trail", Columns: []ColumnDef{
				{Name: "id", Type: "BIGSERIAL", IsSerial: true},
				{Name: "business_id", Type: "INT", NotNull: true},
				{Name: "user_id", Type: "INT"},
				{Name: "user_name", Type: "VARCHAR(100)", NotNull: true},
				{Name: "action", Type: "VARCHAR(30)", NotNull: true},
				{Name: "entity_type", Type: "VARCHAR(30)", NotNull: true},
				{Name: "entity_id", Type: "INT", NotNull: true},
				{Name: "old_values", Type: "JSONB"},
				{Name: "new_values", Type: "JSONB"},
				{Name: "ip_address", Type: "VARCHAR(45)"},
				{Name: "created_at", Type: "TIMESTAMPTZ", NotNull: true, Default: "now()"},
			}},
			{Name: "trial_balance", Columns: []ColumnDef{
				{Name: "id", Type: "BIGSERIAL", IsSerial: true},
				{Name: "business_id", Type: "INT", NotNull: true},
				{Name: "fiscal_period_id", Type: "INT", NotNull: true},
				{Name: "account_id", Type: "INT", NotNull: true},
				{Name: "beginning_balance", Type: "NUMERIC(14,2)", NotNull: true},
				{Name: "total_debits", Type: "NUMERIC(14,2)", NotNull: true},
				{Name: "total_credits", Type: "NUMERIC(14,2)", NotNull: true},
				{Name: "ending_balance", Type: "NUMERIC(14,2)", NotNull: true},
				{Name: "generated_at", Type: "TIMESTAMPTZ", NotNull: true, Default: "now()"},
			}},

			// ──────────────────────────────────────────────
			// RBAC tables (5)
			// ──────────────────────────────────────────────
			{Name: "users", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "business_id", Type: "INT", NotNull: true},
				{Name: "email", Type: "VARCHAR(255)", NotNull: true},
				{Name: "password_hash", Type: "VARCHAR(255)", NotNull: true},
				{Name: "full_name", Type: "VARCHAR(200)", NotNull: true},
				{Name: "status", Type: "VARCHAR(20)", NotNull: true, Default: "'active'"},
				{Name: "last_login_at", Type: "TIMESTAMPTZ"},
				{Name: "created_at", Type: "TIMESTAMPTZ", NotNull: true, Default: "now()"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "roles", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "business_id", Type: "INT", NotNull: true},
				{Name: "name", Type: "VARCHAR(50)", NotNull: true},
				{Name: "description", Type: "TEXT"},
				{Name: "is_system", Type: "BOOLEAN", NotNull: true, Default: "false"},
				{Name: "created_at", Type: "TIMESTAMPTZ", NotNull: true, Default: "now()"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "permissions", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "resource", Type: "VARCHAR(50)", NotNull: true},
				{Name: "action", Type: "VARCHAR(30)", NotNull: true},
				{Name: "description", Type: "TEXT"},
			}},
			{Name: "role_permissions", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "role_id", Type: "INT", NotNull: true},
				{Name: "permission_id", Type: "INT", NotNull: true},
				{Name: "granted_at", Type: "TIMESTAMPTZ", NotNull: true, Default: "now()"},
			}},
			{Name: "user_roles", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "user_id", Type: "INT", NotNull: true},
				{Name: "role_id", Type: "INT", NotNull: true},
				{Name: "granted_at", Type: "TIMESTAMPTZ", NotNull: true, Default: "now()"},
				{Name: "granted_by", Type: "INT"},
			}},

			// ──────────────────────────────────────────────
			// Document management tables (8)
			// ──────────────────────────────────────────────
			{Name: "documents", Columns: []ColumnDef{
				{Name: "id", Type: "BIGSERIAL", IsSerial: true},
				{Name: "business_id", Type: "INT", NotNull: true},
				{Name: "document_type", Type: "VARCHAR(30)", NotNull: true},
				{Name: "title", Type: "VARCHAR(300)", NotNull: true},
				{Name: "description", Type: "TEXT"},
				{Name: "status", Type: "VARCHAR(20)", NotNull: true, Default: "'draft'"},
				{Name: "engagement_id", Type: "INT"},
				{Name: "fiscal_period_id", Type: "INT"},
				{Name: "metadata", Type: "JSONB"},
				{Name: "created_by", Type: "INT", NotNull: true},
				{Name: "created_at", Type: "TIMESTAMPTZ", NotNull: true, Default: "now()"},
				{Name: "updated_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "document_versions", Columns: []ColumnDef{
				{Name: "id", Type: "BIGSERIAL", IsSerial: true},
				{Name: "document_id", Type: "INT", NotNull: true},
				{Name: "version_number", Type: "INT", NotNull: true},
				{Name: "file_path", Type: "TEXT", NotNull: true},
				{Name: "file_size_bytes", Type: "BIGINT", NotNull: true},
				{Name: "content_hash", Type: "VARCHAR(64)", NotNull: true},
				{Name: "change_summary", Type: "TEXT"},
				{Name: "created_by", Type: "INT", NotNull: true},
				{Name: "created_at", Type: "TIMESTAMPTZ", NotNull: true, Default: "now()"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "annotations", Columns: []ColumnDef{
				{Name: "id", Type: "BIGSERIAL", IsSerial: true},
				{Name: "document_version_id", Type: "INT", NotNull: true},
				{Name: "author_id", Type: "INT", NotNull: true},
				{Name: "annotation_type", Type: "VARCHAR(20)", NotNull: true, Default: "'comment'"},
				{Name: "content", Type: "TEXT", NotNull: true},
				{Name: "page_number", Type: "INT"},
				{Name: "position_x", Type: "INT"},
				{Name: "position_y", Type: "INT"},
				{Name: "resolved_at", Type: "TIMESTAMPTZ"},
				{Name: "resolved_by", Type: "INT"},
				{Name: "created_at", Type: "TIMESTAMPTZ", NotNull: true, Default: "now()"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "regulatory_filings", Columns: []ColumnDef{
				{Name: "id", Type: "BIGSERIAL", IsSerial: true},
				{Name: "business_id", Type: "INT", NotNull: true},
				{Name: "document_id", Type: "INT"},
				{Name: "filing_type", Type: "VARCHAR(30)", NotNull: true},
				{Name: "jurisdiction", Type: "VARCHAR(50)", NotNull: true},
				{Name: "filing_period_start", Type: "DATE", NotNull: true},
				{Name: "filing_period_end", Type: "DATE", NotNull: true},
				{Name: "due_date", Type: "DATE", NotNull: true},
				{Name: "filed_date", Type: "DATE"},
				{Name: "confirmation_number", Type: "VARCHAR(50)"},
				{Name: "status", Type: "VARCHAR(20)", NotNull: true, Default: "'pending'"},
				{Name: "amount_due", Type: "NUMERIC(14,2)"},
				{Name: "amount_paid", Type: "NUMERIC(14,2)"},
				{Name: "metadata", Type: "JSONB"},
				{Name: "filed_by", Type: "INT"},
				{Name: "created_at", Type: "TIMESTAMPTZ", NotNull: true, Default: "now()"},
			}},
			{Name: "citations", Columns: []ColumnDef{
				{Name: "id", Type: "BIGSERIAL", IsSerial: true},
				{Name: "source_document_id", Type: "INT", NotNull: true},
				{Name: "target_document_id", Type: "INT", NotNull: true},
				{Name: "citation_type", Type: "VARCHAR(30)", NotNull: true, Default: "'reference'"},
				{Name: "description", Type: "TEXT"},
				{Name: "page_number", Type: "INT"},
				{Name: "created_by", Type: "INT", NotNull: true},
				{Name: "created_at", Type: "TIMESTAMPTZ", NotNull: true, Default: "now()"},
			}},
			{Name: "engagement_letters", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "business_id", Type: "INT", NotNull: true},
				{Name: "document_id", Type: "INT"},
				{Name: "client_name", Type: "VARCHAR(200)", NotNull: true},
				{Name: "engagement_type", Type: "VARCHAR(30)", NotNull: true},
				{Name: "effective_date", Type: "DATE", NotNull: true},
				{Name: "expiration_date", Type: "DATE"},
				{Name: "fee_amount", Type: "NUMERIC(14,2)"},
				{Name: "fee_structure", Type: "VARCHAR(30)", NotNull: true, Default: "'fixed'"},
				{Name: "status", Type: "VARCHAR(20)", NotNull: true, Default: "'draft'"},
				{Name: "signed_at", Type: "TIMESTAMPTZ"},
				{Name: "signed_by", Type: "INT"},
				{Name: "created_by", Type: "INT", NotNull: true},
				{Name: "created_at", Type: "TIMESTAMPTZ", NotNull: true, Default: "now()"},
			}},
			{Name: "workpapers", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "business_id", Type: "INT", NotNull: true},
				{Name: "document_id", Type: "INT"},
				{Name: "fiscal_period_id", Type: "INT", NotNull: true},
				{Name: "workpaper_ref", Type: "VARCHAR(20)", NotNull: true},
				{Name: "title", Type: "VARCHAR(200)", NotNull: true},
				{Name: "section", Type: "VARCHAR(50)", NotNull: true},
				{Name: "status", Type: "VARCHAR(20)", NotNull: true, Default: "'in_progress'"},
				{Name: "prepared_by", Type: "INT", NotNull: true},
				{Name: "reviewed_by", Type: "INT"},
				{Name: "prepared_at", Type: "TIMESTAMPTZ", NotNull: true, Default: "now()"},
				{Name: "reviewed_at", Type: "TIMESTAMPTZ"},
			}},
			{Name: "review_comments", Columns: []ColumnDef{
				{Name: "id", Type: "BIGSERIAL", IsSerial: true},
				{Name: "workpaper_id", Type: "INT", NotNull: true},
				{Name: "author_id", Type: "INT", NotNull: true},
				{Name: "comment_type", Type: "VARCHAR(20)", NotNull: true, Default: "'note'"},
				{Name: "content", Type: "TEXT", NotNull: true},
				{Name: "severity", Type: "VARCHAR(20)", NotNull: true, Default: "'info'"},
				{Name: "resolved_at", Type: "TIMESTAMPTZ"},
				{Name: "resolved_by", Type: "INT"},
				{Name: "created_at", Type: "TIMESTAMPTZ", NotNull: true, Default: "now()"},
			}},
		},
		Indexes: []IndexDef{
			// ── Original 16 table indexes ──
			{Name: "idx_aa_biz_ein", Table: "businesses", Columns: []string{"ein"}, Unique: true},
			{Name: "idx_aa_biz_deleted", Table: "businesses", Columns: []string{"deleted_at"}},
			{Name: "idx_aa_biz_created_by", Table: "businesses", Columns: []string{"created_by"}},
			{Name: "idx_aa_cust_business", Table: "customers", Columns: []string{"business_id"}},
			{Name: "idx_aa_cust_deleted", Table: "customers", Columns: []string{"deleted_at"}},
			{Name: "idx_aa_vend_business", Table: "vendors", Columns: []string{"business_id"}},
			{Name: "idx_aa_vend_deleted", Table: "vendors", Columns: []string{"deleted_at"}},
			{Name: "idx_aa_coa_business", Table: "chart_of_accounts", Columns: []string{"business_id"}},
			{Name: "idx_aa_coa_code", Table: "chart_of_accounts", Columns: []string{"business_id", "account_code"}, Unique: true},
			{Name: "idx_aa_coa_type", Table: "chart_of_accounts", Columns: []string{"account_type"}},
			{Name: "idx_aa_coa_parent", Table: "chart_of_accounts", Columns: []string{"parent_account_id"}},
			{Name: "idx_aa_fp_business", Table: "fiscal_periods", Columns: []string{"business_id"}},
			{Name: "idx_aa_fp_dates", Table: "fiscal_periods", Columns: []string{"start_date", "end_date"}},
			{Name: "idx_aa_fp_status", Table: "fiscal_periods", Columns: []string{"status"}},
			{Name: "idx_aa_inv_business", Table: "invoices", Columns: []string{"business_id"}},
			{Name: "idx_aa_inv_customer", Table: "invoices", Columns: []string{"customer_id"}},
			{Name: "idx_aa_inv_period", Table: "invoices", Columns: []string{"fiscal_period_id"}},
			{Name: "idx_aa_inv_number", Table: "invoices", Columns: []string{"business_id", "invoice_number"}, Unique: true},
			{Name: "idx_aa_inv_date", Table: "invoices", Columns: []string{"invoice_date"}},
			{Name: "idx_aa_inv_due", Table: "invoices", Columns: []string{"due_date"}},
			{Name: "idx_aa_inv_status", Table: "invoices", Columns: []string{"status"}},
			{Name: "idx_aa_inv_deleted", Table: "invoices", Columns: []string{"deleted_at"}},
			{Name: "idx_aa_inv_created_by", Table: "invoices", Columns: []string{"created_by"}},
			{Name: "idx_aa_bill_business", Table: "bills", Columns: []string{"business_id"}},
			{Name: "idx_aa_bill_vendor", Table: "bills", Columns: []string{"vendor_id"}},
			{Name: "idx_aa_bill_period", Table: "bills", Columns: []string{"fiscal_period_id"}},
			{Name: "idx_aa_bill_number", Table: "bills", Columns: []string{"business_id", "bill_number"}, Unique: true},
			{Name: "idx_aa_bill_date", Table: "bills", Columns: []string{"bill_date"}},
			{Name: "idx_aa_bill_due", Table: "bills", Columns: []string{"due_date"}},
			{Name: "idx_aa_bill_status", Table: "bills", Columns: []string{"status"}},
			{Name: "idx_aa_bill_deleted", Table: "bills", Columns: []string{"deleted_at"}},
			{Name: "idx_aa_bill_created_by", Table: "bills", Columns: []string{"created_by"}},
			{Name: "idx_aa_pr_business", Table: "payments_received", Columns: []string{"business_id"}},
			{Name: "idx_aa_pr_customer", Table: "payments_received", Columns: []string{"customer_id"}},
			{Name: "idx_aa_pr_invoice", Table: "payments_received", Columns: []string{"invoice_id"}},
			{Name: "idx_aa_pr_period", Table: "payments_received", Columns: []string{"fiscal_period_id"}},
			{Name: "idx_aa_pr_date", Table: "payments_received", Columns: []string{"payment_date"}},
			{Name: "idx_aa_pm_business", Table: "payments_made", Columns: []string{"business_id"}},
			{Name: "idx_aa_pm_vendor", Table: "payments_made", Columns: []string{"vendor_id"}},
			{Name: "idx_aa_pm_bill", Table: "payments_made", Columns: []string{"bill_id"}},
			{Name: "idx_aa_pm_period", Table: "payments_made", Columns: []string{"fiscal_period_id"}},
			{Name: "idx_aa_pm_date", Table: "payments_made", Columns: []string{"payment_date"}},
			{Name: "idx_aa_je_business", Table: "journal_entries", Columns: []string{"business_id"}},
			{Name: "idx_aa_je_period", Table: "journal_entries", Columns: []string{"fiscal_period_id"}},
			{Name: "idx_aa_je_date", Table: "journal_entries", Columns: []string{"entry_date"}},
			{Name: "idx_aa_je_type", Table: "journal_entries", Columns: []string{"entry_type"}},
			{Name: "idx_aa_je_source", Table: "journal_entries", Columns: []string{"source_type", "source_id"}},
			{Name: "idx_aa_je_deleted", Table: "journal_entries", Columns: []string{"deleted_at"}},
			{Name: "idx_aa_je_created_by", Table: "journal_entries", Columns: []string{"created_by"}},
			{Name: "idx_aa_jl_entry", Table: "journal_lines", Columns: []string{"journal_entry_id"}},
			{Name: "idx_aa_jl_account", Table: "journal_lines", Columns: []string{"account_id"}},
			{Name: "idx_aa_jl_entity", Table: "journal_lines", Columns: []string{"entity_type", "entity_id"}},
			{Name: "idx_aa_ar_business", Table: "ar_aging", Columns: []string{"business_id"}},
			{Name: "idx_aa_ar_customer", Table: "ar_aging", Columns: []string{"customer_id"}},
			{Name: "idx_aa_ar_invoice", Table: "ar_aging", Columns: []string{"invoice_id"}},
			{Name: "idx_aa_ar_date", Table: "ar_aging", Columns: []string{"as_of_date"}},
			{Name: "idx_aa_ap_business", Table: "ap_aging", Columns: []string{"business_id"}},
			{Name: "idx_aa_ap_vendor", Table: "ap_aging", Columns: []string{"vendor_id"}},
			{Name: "idx_aa_ap_bill", Table: "ap_aging", Columns: []string{"bill_id"}},
			{Name: "idx_aa_ap_date", Table: "ap_aging", Columns: []string{"as_of_date"}},
			{Name: "idx_aa_bud_business", Table: "budgets", Columns: []string{"business_id"}},
			{Name: "idx_aa_bud_account", Table: "budgets", Columns: []string{"account_id"}},
			{Name: "idx_aa_bud_period", Table: "budgets", Columns: []string{"fiscal_period_id"}},
			{Name: "idx_aa_bud_uniq", Table: "budgets", Columns: []string{"business_id", "account_id", "fiscal_period_id"}, Unique: true},
			{Name: "idx_aa_audit_business", Table: "audit_trail", Columns: []string{"business_id"}},
			{Name: "idx_aa_audit_user", Table: "audit_trail", Columns: []string{"user_id"}},
			{Name: "idx_aa_audit_entity", Table: "audit_trail", Columns: []string{"entity_type", "entity_id"}},
			{Name: "idx_aa_audit_action", Table: "audit_trail", Columns: []string{"action"}},
			{Name: "idx_aa_audit_created", Table: "audit_trail", Columns: []string{"created_at"}},
			{Name: "idx_aa_tb_business", Table: "trial_balance", Columns: []string{"business_id"}},
			{Name: "idx_aa_tb_period", Table: "trial_balance", Columns: []string{"fiscal_period_id"}},
			{Name: "idx_aa_tb_account", Table: "trial_balance", Columns: []string{"account_id"}},
			{Name: "idx_aa_tb_uniq", Table: "trial_balance", Columns: []string{"business_id", "fiscal_period_id", "account_id"}, Unique: true},

			// ── RBAC indexes ──
			{Name: "idx_aa_usr_business", Table: "users", Columns: []string{"business_id"}},
			{Name: "idx_aa_usr_email", Table: "users", Columns: []string{"email"}, Unique: true},
			{Name: "idx_aa_usr_status", Table: "users", Columns: []string{"status"}},
			{Name: "idx_aa_usr_deleted", Table: "users", Columns: []string{"deleted_at"}},
			{Name: "idx_aa_role_business", Table: "roles", Columns: []string{"business_id"}},
			{Name: "idx_aa_role_name", Table: "roles", Columns: []string{"business_id", "name"}, Unique: true},
			{Name: "idx_aa_role_deleted", Table: "roles", Columns: []string{"deleted_at"}},
			{Name: "idx_aa_perm_resource", Table: "permissions", Columns: []string{"resource", "action"}, Unique: true},
			{Name: "idx_aa_rp_role", Table: "role_permissions", Columns: []string{"role_id"}},
			{Name: "idx_aa_rp_perm", Table: "role_permissions", Columns: []string{"permission_id"}},
			{Name: "idx_aa_rp_uniq", Table: "role_permissions", Columns: []string{"role_id", "permission_id"}, Unique: true},
			{Name: "idx_aa_ur_user", Table: "user_roles", Columns: []string{"user_id"}},
			{Name: "idx_aa_ur_role", Table: "user_roles", Columns: []string{"role_id"}},
			{Name: "idx_aa_ur_uniq", Table: "user_roles", Columns: []string{"user_id", "role_id"}, Unique: true},

			// ── Document management indexes ──
			{Name: "idx_aa_doc_business", Table: "documents", Columns: []string{"business_id"}},
			{Name: "idx_aa_doc_type", Table: "documents", Columns: []string{"document_type"}},
			{Name: "idx_aa_doc_status", Table: "documents", Columns: []string{"status"}},
			{Name: "idx_aa_doc_engagement", Table: "documents", Columns: []string{"engagement_id"}},
			{Name: "idx_aa_doc_period", Table: "documents", Columns: []string{"fiscal_period_id"}},
			{Name: "idx_aa_doc_created_by", Table: "documents", Columns: []string{"created_by"}},
			{Name: "idx_aa_doc_created", Table: "documents", Columns: []string{"created_at"}},
			{Name: "idx_aa_doc_deleted", Table: "documents", Columns: []string{"deleted_at"}},
			{Name: "idx_aa_dv_document", Table: "document_versions", Columns: []string{"document_id"}},
			{Name: "idx_aa_dv_uniq", Table: "document_versions", Columns: []string{"document_id", "version_number"}, Unique: true},
			{Name: "idx_aa_dv_created_by", Table: "document_versions", Columns: []string{"created_by"}},
			{Name: "idx_aa_dv_deleted", Table: "document_versions", Columns: []string{"deleted_at"}},
			{Name: "idx_aa_ann_version", Table: "annotations", Columns: []string{"document_version_id"}},
			{Name: "idx_aa_ann_author", Table: "annotations", Columns: []string{"author_id"}},
			{Name: "idx_aa_ann_type", Table: "annotations", Columns: []string{"annotation_type"}},
			{Name: "idx_aa_ann_deleted", Table: "annotations", Columns: []string{"deleted_at"}},
			{Name: "idx_aa_rf_business", Table: "regulatory_filings", Columns: []string{"business_id"}},
			{Name: "idx_aa_rf_document", Table: "regulatory_filings", Columns: []string{"document_id"}},
			{Name: "idx_aa_rf_type", Table: "regulatory_filings", Columns: []string{"filing_type"}},
			{Name: "idx_aa_rf_jurisdiction", Table: "regulatory_filings", Columns: []string{"jurisdiction"}},
			{Name: "idx_aa_rf_status", Table: "regulatory_filings", Columns: []string{"status"}},
			{Name: "idx_aa_rf_due", Table: "regulatory_filings", Columns: []string{"due_date"}},
			{Name: "idx_aa_rf_filed", Table: "regulatory_filings", Columns: []string{"filed_date"}},
			{Name: "idx_aa_cit_source", Table: "citations", Columns: []string{"source_document_id"}},
			{Name: "idx_aa_cit_target", Table: "citations", Columns: []string{"target_document_id"}},
			{Name: "idx_aa_cit_type", Table: "citations", Columns: []string{"citation_type"}},
			{Name: "idx_aa_el_business", Table: "engagement_letters", Columns: []string{"business_id"}},
			{Name: "idx_aa_el_document", Table: "engagement_letters", Columns: []string{"document_id"}},
			{Name: "idx_aa_el_status", Table: "engagement_letters", Columns: []string{"status"}},
			{Name: "idx_aa_el_effective", Table: "engagement_letters", Columns: []string{"effective_date"}},
			{Name: "idx_aa_el_type", Table: "engagement_letters", Columns: []string{"engagement_type"}},
			{Name: "idx_aa_wp_business", Table: "workpapers", Columns: []string{"business_id"}},
			{Name: "idx_aa_wp_document", Table: "workpapers", Columns: []string{"document_id"}},
			{Name: "idx_aa_wp_period", Table: "workpapers", Columns: []string{"fiscal_period_id"}},
			{Name: "idx_aa_wp_ref", Table: "workpapers", Columns: []string{"business_id", "workpaper_ref"}, Unique: true},
			{Name: "idx_aa_wp_status", Table: "workpapers", Columns: []string{"status"}},
			{Name: "idx_aa_wp_prepared_by", Table: "workpapers", Columns: []string{"prepared_by"}},
			{Name: "idx_aa_wp_reviewed_by", Table: "workpapers", Columns: []string{"reviewed_by"}},
			{Name: "idx_aa_rc_workpaper", Table: "review_comments", Columns: []string{"workpaper_id"}},
			{Name: "idx_aa_rc_author", Table: "review_comments", Columns: []string{"author_id"}},
			{Name: "idx_aa_rc_type", Table: "review_comments", Columns: []string{"comment_type"}},
			{Name: "idx_aa_rc_severity", Table: "review_comments", Columns: []string{"severity"}},
		},
		ForeignKeys: []FKDef{
			// ── Original 16 table FKs ──
			{Name: "fk_aa_cust_biz", Table: "customers", Column: "business_id", RefTable: "businesses", RefColumn: "id"},
			{Name: "fk_aa_vend_biz", Table: "vendors", Column: "business_id", RefTable: "businesses", RefColumn: "id"},
			{Name: "fk_aa_coa_biz", Table: "chart_of_accounts", Column: "business_id", RefTable: "businesses", RefColumn: "id"},
			{Name: "fk_aa_coa_parent", Table: "chart_of_accounts", Column: "parent_account_id", RefTable: "chart_of_accounts", RefColumn: "id"},
			{Name: "fk_aa_fp_biz", Table: "fiscal_periods", Column: "business_id", RefTable: "businesses", RefColumn: "id"},
			{Name: "fk_aa_inv_biz", Table: "invoices", Column: "business_id", RefTable: "businesses", RefColumn: "id"},
			{Name: "fk_aa_inv_cust", Table: "invoices", Column: "customer_id", RefTable: "customers", RefColumn: "id"},
			{Name: "fk_aa_inv_period", Table: "invoices", Column: "fiscal_period_id", RefTable: "fiscal_periods", RefColumn: "id"},
			{Name: "fk_aa_inv_created_by", Table: "invoices", Column: "created_by", RefTable: "users", RefColumn: "id"},
			{Name: "fk_aa_bill_biz", Table: "bills", Column: "business_id", RefTable: "businesses", RefColumn: "id"},
			{Name: "fk_aa_bill_vend", Table: "bills", Column: "vendor_id", RefTable: "vendors", RefColumn: "id"},
			{Name: "fk_aa_bill_period", Table: "bills", Column: "fiscal_period_id", RefTable: "fiscal_periods", RefColumn: "id"},
			{Name: "fk_aa_bill_created_by", Table: "bills", Column: "created_by", RefTable: "users", RefColumn: "id"},
			{Name: "fk_aa_pr_biz", Table: "payments_received", Column: "business_id", RefTable: "businesses", RefColumn: "id"},
			{Name: "fk_aa_pr_cust", Table: "payments_received", Column: "customer_id", RefTable: "customers", RefColumn: "id"},
			{Name: "fk_aa_pr_inv", Table: "payments_received", Column: "invoice_id", RefTable: "invoices", RefColumn: "id"},
			{Name: "fk_aa_pr_period", Table: "payments_received", Column: "fiscal_period_id", RefTable: "fiscal_periods", RefColumn: "id"},
			{Name: "fk_aa_pr_acct", Table: "payments_received", Column: "deposit_account_id", RefTable: "chart_of_accounts", RefColumn: "id"},
			{Name: "fk_aa_pm_biz", Table: "payments_made", Column: "business_id", RefTable: "businesses", RefColumn: "id"},
			{Name: "fk_aa_pm_vend", Table: "payments_made", Column: "vendor_id", RefTable: "vendors", RefColumn: "id"},
			{Name: "fk_aa_pm_bill", Table: "payments_made", Column: "bill_id", RefTable: "bills", RefColumn: "id"},
			{Name: "fk_aa_pm_period", Table: "payments_made", Column: "fiscal_period_id", RefTable: "fiscal_periods", RefColumn: "id"},
			{Name: "fk_aa_pm_bank", Table: "payments_made", Column: "bank_account_id", RefTable: "chart_of_accounts", RefColumn: "id"},
			{Name: "fk_aa_je_biz", Table: "journal_entries", Column: "business_id", RefTable: "businesses", RefColumn: "id"},
			{Name: "fk_aa_je_period", Table: "journal_entries", Column: "fiscal_period_id", RefTable: "fiscal_periods", RefColumn: "id"},
			{Name: "fk_aa_je_created_by", Table: "journal_entries", Column: "created_by", RefTable: "users", RefColumn: "id"},
			{Name: "fk_aa_jl_entry", Table: "journal_lines", Column: "journal_entry_id", RefTable: "journal_entries", RefColumn: "id"},
			{Name: "fk_aa_jl_acct", Table: "journal_lines", Column: "account_id", RefTable: "chart_of_accounts", RefColumn: "id"},
			{Name: "fk_aa_ar_biz", Table: "ar_aging", Column: "business_id", RefTable: "businesses", RefColumn: "id"},
			{Name: "fk_aa_ar_cust", Table: "ar_aging", Column: "customer_id", RefTable: "customers", RefColumn: "id"},
			{Name: "fk_aa_ar_inv", Table: "ar_aging", Column: "invoice_id", RefTable: "invoices", RefColumn: "id"},
			{Name: "fk_aa_ap_biz", Table: "ap_aging", Column: "business_id", RefTable: "businesses", RefColumn: "id"},
			{Name: "fk_aa_ap_vend", Table: "ap_aging", Column: "vendor_id", RefTable: "vendors", RefColumn: "id"},
			{Name: "fk_aa_ap_bill", Table: "ap_aging", Column: "bill_id", RefTable: "bills", RefColumn: "id"},
			{Name: "fk_aa_bud_biz", Table: "budgets", Column: "business_id", RefTable: "businesses", RefColumn: "id"},
			{Name: "fk_aa_bud_acct", Table: "budgets", Column: "account_id", RefTable: "chart_of_accounts", RefColumn: "id"},
			{Name: "fk_aa_bud_period", Table: "budgets", Column: "fiscal_period_id", RefTable: "fiscal_periods", RefColumn: "id"},
			{Name: "fk_aa_audit_biz", Table: "audit_trail", Column: "business_id", RefTable: "businesses", RefColumn: "id"},
			{Name: "fk_aa_audit_user", Table: "audit_trail", Column: "user_id", RefTable: "users", RefColumn: "id"},
			{Name: "fk_aa_tb_biz", Table: "trial_balance", Column: "business_id", RefTable: "businesses", RefColumn: "id"},
			{Name: "fk_aa_tb_period", Table: "trial_balance", Column: "fiscal_period_id", RefTable: "fiscal_periods", RefColumn: "id"},
			{Name: "fk_aa_tb_acct", Table: "trial_balance", Column: "account_id", RefTable: "chart_of_accounts", RefColumn: "id"},
			// businesses.created_by → users omitted: circular with users.business_id → businesses

			// ── RBAC FKs ──
			{Name: "fk_aa_usr_biz", Table: "users", Column: "business_id", RefTable: "businesses", RefColumn: "id"},
			{Name: "fk_aa_role_biz", Table: "roles", Column: "business_id", RefTable: "businesses", RefColumn: "id"},
			{Name: "fk_aa_rp_role", Table: "role_permissions", Column: "role_id", RefTable: "roles", RefColumn: "id"},
			{Name: "fk_aa_rp_perm", Table: "role_permissions", Column: "permission_id", RefTable: "permissions", RefColumn: "id"},
			{Name: "fk_aa_ur_user", Table: "user_roles", Column: "user_id", RefTable: "users", RefColumn: "id"},
			{Name: "fk_aa_ur_role", Table: "user_roles", Column: "role_id", RefTable: "roles", RefColumn: "id"},
			{Name: "fk_aa_ur_granted_by", Table: "user_roles", Column: "granted_by", RefTable: "users", RefColumn: "id"},

			// ── Document management FKs ──
			{Name: "fk_aa_doc_biz", Table: "documents", Column: "business_id", RefTable: "businesses", RefColumn: "id"},
			{Name: "fk_aa_doc_period", Table: "documents", Column: "fiscal_period_id", RefTable: "fiscal_periods", RefColumn: "id"},
			{Name: "fk_aa_doc_created_by", Table: "documents", Column: "created_by", RefTable: "users", RefColumn: "id"},
			{Name: "fk_aa_dv_doc", Table: "document_versions", Column: "document_id", RefTable: "documents", RefColumn: "id"},
			{Name: "fk_aa_dv_created_by", Table: "document_versions", Column: "created_by", RefTable: "users", RefColumn: "id"},
			{Name: "fk_aa_ann_version", Table: "annotations", Column: "document_version_id", RefTable: "document_versions", RefColumn: "id"},
			{Name: "fk_aa_ann_author", Table: "annotations", Column: "author_id", RefTable: "users", RefColumn: "id"},
			{Name: "fk_aa_ann_resolved_by", Table: "annotations", Column: "resolved_by", RefTable: "users", RefColumn: "id"},
			{Name: "fk_aa_rf_biz", Table: "regulatory_filings", Column: "business_id", RefTable: "businesses", RefColumn: "id"},
			{Name: "fk_aa_rf_doc", Table: "regulatory_filings", Column: "document_id", RefTable: "documents", RefColumn: "id"},
			{Name: "fk_aa_rf_filed_by", Table: "regulatory_filings", Column: "filed_by", RefTable: "users", RefColumn: "id"},
			{Name: "fk_aa_cit_source", Table: "citations", Column: "source_document_id", RefTable: "documents", RefColumn: "id"},
			{Name: "fk_aa_cit_target", Table: "citations", Column: "target_document_id", RefTable: "documents", RefColumn: "id"},
			{Name: "fk_aa_cit_created_by", Table: "citations", Column: "created_by", RefTable: "users", RefColumn: "id"},
			{Name: "fk_aa_el_biz", Table: "engagement_letters", Column: "business_id", RefTable: "businesses", RefColumn: "id"},
			{Name: "fk_aa_el_doc", Table: "engagement_letters", Column: "document_id", RefTable: "documents", RefColumn: "id"},
			{Name: "fk_aa_el_signed_by", Table: "engagement_letters", Column: "signed_by", RefTable: "users", RefColumn: "id"},
			{Name: "fk_aa_el_created_by", Table: "engagement_letters", Column: "created_by", RefTable: "users", RefColumn: "id"},
			{Name: "fk_aa_wp_biz", Table: "workpapers", Column: "business_id", RefTable: "businesses", RefColumn: "id"},
			{Name: "fk_aa_wp_doc", Table: "workpapers", Column: "document_id", RefTable: "documents", RefColumn: "id"},
			{Name: "fk_aa_wp_period", Table: "workpapers", Column: "fiscal_period_id", RefTable: "fiscal_periods", RefColumn: "id"},
			{Name: "fk_aa_wp_prepared_by", Table: "workpapers", Column: "prepared_by", RefTable: "users", RefColumn: "id"},
			{Name: "fk_aa_wp_reviewed_by", Table: "workpapers", Column: "reviewed_by", RefTable: "users", RefColumn: "id"},
			{Name: "fk_aa_rc_workpaper", Table: "review_comments", Column: "workpaper_id", RefTable: "workpapers", RefColumn: "id"},
			{Name: "fk_aa_rc_author", Table: "review_comments", Column: "author_id", RefTable: "users", RefColumn: "id"},
			{Name: "fk_aa_rc_resolved_by", Table: "review_comments", Column: "resolved_by", RefTable: "users", RefColumn: "id"},
		},
	}
}

// healthcareDomain models a comprehensive EHR system with integrated RBAC and IoT
// medical device telemetry. 26 tables with soft-delete markers on every table, JSONB
// clinical data, deep join chains (12+ way for patient summaries), RBAC permission
// checks layered on business queries, and IoT sensor readings for bedside monitors.
func healthcareDomain() Domain {
	return Domain{
		Name:        "healthcare",
		Description: "Full EHR with 34 tables: clinical + RBAC + IoT telemetry + medical supply chain, soft-delete, deep joins",
		Tables: []TableDef{
			// --- Core clinical tables ---
			{Name: "patients", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "mrn", Type: "VARCHAR(20)", NotNull: true},
				{Name: "name", Type: "VARCHAR(200)", NotNull: true},
				{Name: "date_of_birth", Type: "DATE", NotNull: true},
				{Name: "gender", Type: "VARCHAR(10)", NotNull: true},
				{Name: "blood_type", Type: "VARCHAR(10)"},
				{Name: "email", Type: "VARCHAR(255)"},
				{Name: "phone", Type: "VARCHAR(20)"},
				{Name: "address", Type: "TEXT"},
				{Name: "emergency_contact", Type: "VARCHAR(200)"},
				{Name: "created_by", Type: "INT"},
				{Name: "created_at", Type: "TIMESTAMPTZ", NotNull: true, Default: "now()"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "providers", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "user_id", Type: "INT"},
				{Name: "npi", Type: "VARCHAR(10)", NotNull: true},
				{Name: "name", Type: "VARCHAR(200)", NotNull: true},
				{Name: "specialty", Type: "VARCHAR(50)", NotNull: true},
				{Name: "department", Type: "VARCHAR(100)"},
				{Name: "license_number", Type: "VARCHAR(30)"},
				{Name: "is_active", Type: "BOOLEAN", NotNull: true, Default: "true"},
				{Name: "created_at", Type: "TIMESTAMPTZ", NotNull: true, Default: "now()"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "encounters", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "patient_id", Type: "INT", NotNull: true},
				{Name: "provider_id", Type: "INT", NotNull: true},
				{Name: "encounter_type", Type: "VARCHAR(30)", NotNull: true},
				{Name: "admission_date", Type: "TIMESTAMPTZ", NotNull: true},
				{Name: "discharge_date", Type: "TIMESTAMPTZ"},
				{Name: "status", Type: "VARCHAR(20)", NotNull: true, Default: "'active'"},
				{Name: "facility", Type: "VARCHAR(100)", NotNull: true},
				{Name: "chief_complaint", Type: "TEXT"},
				{Name: "notes", Type: "TEXT"},
				{Name: "clinical_data", Type: "JSONB"},
				{Name: "created_by", Type: "INT"},
				{Name: "created_at", Type: "TIMESTAMPTZ", NotNull: true, Default: "now()"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "diagnoses", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "encounter_id", Type: "INT", NotNull: true},
				{Name: "icd_code", Type: "VARCHAR(10)", NotNull: true},
				{Name: "description", Type: "TEXT", NotNull: true},
				{Name: "diagnosis_type", Type: "VARCHAR(20)", NotNull: true, Default: "'secondary'"},
				{Name: "diagnosed_at", Type: "TIMESTAMPTZ", NotNull: true},
				{Name: "diagnosed_by", Type: "INT", NotNull: true},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "procedures", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "encounter_id", Type: "INT", NotNull: true},
				{Name: "cpt_code", Type: "VARCHAR(10)", NotNull: true},
				{Name: "description", Type: "TEXT", NotNull: true},
				{Name: "performed_at", Type: "TIMESTAMPTZ", NotNull: true},
				{Name: "performed_by", Type: "INT", NotNull: true},
				{Name: "duration_minutes", Type: "INT"},
				{Name: "status", Type: "VARCHAR(20)", NotNull: true, Default: "'completed'"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "medications", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "ndc_code", Type: "VARCHAR(12)", NotNull: true},
				{Name: "name", Type: "VARCHAR(200)", NotNull: true},
				{Name: "generic_name", Type: "VARCHAR(200)"},
				{Name: "drug_class", Type: "VARCHAR(50)", NotNull: true},
				{Name: "strength", Type: "VARCHAR(30)"},
				{Name: "unit", Type: "VARCHAR(20)"},
				{Name: "is_active", Type: "BOOLEAN", NotNull: true, Default: "true"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "prescriptions", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "encounter_id", Type: "INT", NotNull: true},
				{Name: "medication_id", Type: "INT", NotNull: true},
				{Name: "patient_id", Type: "INT", NotNull: true},
				{Name: "prescribed_by", Type: "INT", NotNull: true},
				{Name: "dosage", Type: "VARCHAR(50)", NotNull: true},
				{Name: "frequency", Type: "VARCHAR(30)", NotNull: true},
				{Name: "start_date", Type: "DATE", NotNull: true},
				{Name: "end_date", Type: "DATE"},
				{Name: "refills_remaining", Type: "INT", NotNull: true, Default: "0"},
				{Name: "status", Type: "VARCHAR(20)", NotNull: true, Default: "'active'"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "allergies", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "patient_id", Type: "INT", NotNull: true},
				{Name: "allergen", Type: "VARCHAR(200)", NotNull: true},
				{Name: "allergy_type", Type: "VARCHAR(20)", NotNull: true},
				{Name: "severity", Type: "VARCHAR(20)", NotNull: true},
				{Name: "reaction", Type: "TEXT"},
				{Name: "onset_date", Type: "DATE"},
				{Name: "verified_by", Type: "INT"},
				{Name: "created_at", Type: "TIMESTAMPTZ", NotNull: true, Default: "now()"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "vitals", Columns: []ColumnDef{
				{Name: "id", Type: "BIGSERIAL", IsSerial: true},
				{Name: "encounter_id", Type: "INT", NotNull: true},
				{Name: "patient_id", Type: "INT", NotNull: true},
				{Name: "recorded_by", Type: "INT", NotNull: true},
				{Name: "systolic_bp", Type: "SMALLINT"},
				{Name: "diastolic_bp", Type: "SMALLINT"},
				{Name: "heart_rate", Type: "SMALLINT"},
				{Name: "temperature", Type: "NUMERIC(4,1)"},
				{Name: "respiratory_rate", Type: "SMALLINT"},
				{Name: "o2_saturation", Type: "NUMERIC(4,1)"},
				{Name: "weight_kg", Type: "NUMERIC(5,1)"},
				{Name: "height_cm", Type: "NUMERIC(5,1)"},
				{Name: "recorded_at", Type: "TIMESTAMPTZ", NotNull: true},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "lab_results", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "encounter_id", Type: "INT", NotNull: true},
				{Name: "patient_id", Type: "INT", NotNull: true},
				{Name: "ordered_by", Type: "INT", NotNull: true},
				{Name: "test_name", Type: "VARCHAR(100)", NotNull: true},
				{Name: "result_value", Type: "NUMERIC(12,4)"},
				{Name: "result_unit", Type: "VARCHAR(20)"},
				{Name: "reference_range", Type: "VARCHAR(50)"},
				{Name: "abnormal_flag", Type: "VARCHAR(10)"},
				{Name: "collected_at", Type: "TIMESTAMPTZ", NotNull: true},
				{Name: "resulted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "immunizations", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "patient_id", Type: "INT", NotNull: true},
				{Name: "vaccine_name", Type: "VARCHAR(100)", NotNull: true},
				{Name: "vaccine_code", Type: "VARCHAR(20)", NotNull: true},
				{Name: "lot_number", Type: "VARCHAR(30)"},
				{Name: "administered_by", Type: "INT", NotNull: true},
				{Name: "site", Type: "VARCHAR(30)"},
				{Name: "dose_number", Type: "INT"},
				{Name: "administered_at", Type: "TIMESTAMPTZ", NotNull: true},
				{Name: "next_due_date", Type: "DATE"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "referrals", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "encounter_id", Type: "INT", NotNull: true},
				{Name: "patient_id", Type: "INT", NotNull: true},
				{Name: "referring_provider_id", Type: "INT", NotNull: true},
				{Name: "referred_to_provider_id", Type: "INT"},
				{Name: "referral_reason", Type: "TEXT", NotNull: true},
				{Name: "priority", Type: "VARCHAR(20)", NotNull: true, Default: "'routine'"},
				{Name: "authorization_number", Type: "VARCHAR(30)"},
				{Name: "status", Type: "VARCHAR(20)", NotNull: true, Default: "'pending'"},
				{Name: "created_at", Type: "TIMESTAMPTZ", NotNull: true, Default: "now()"},
				{Name: "completed_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "care_plans", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "patient_id", Type: "INT", NotNull: true},
				{Name: "provider_id", Type: "INT", NotNull: true},
				{Name: "title", Type: "VARCHAR(200)", NotNull: true},
				{Name: "goal", Type: "TEXT", NotNull: true},
				{Name: "interventions", Type: "TEXT"},
				{Name: "start_date", Type: "DATE", NotNull: true},
				{Name: "target_date", Type: "DATE"},
				{Name: "status", Type: "VARCHAR(20)", NotNull: true, Default: "'active'"},
				{Name: "outcome", Type: "TEXT"},
				{Name: "created_at", Type: "TIMESTAMPTZ", NotNull: true, Default: "now()"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "medical_history", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "patient_id", Type: "INT", NotNull: true},
				{Name: "condition", Type: "VARCHAR(200)", NotNull: true},
				{Name: "icd_code", Type: "VARCHAR(10)"},
				{Name: "history_type", Type: "VARCHAR(20)", NotNull: true},
				{Name: "onset_date", Type: "DATE"},
				{Name: "resolution_date", Type: "DATE"},
				{Name: "notes", Type: "TEXT"},
				{Name: "recorded_by", Type: "INT"},
				{Name: "created_at", Type: "TIMESTAMPTZ", NotNull: true, Default: "now()"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "billing_claims", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "encounter_id", Type: "INT", NotNull: true},
				{Name: "patient_id", Type: "INT", NotNull: true},
				{Name: "insurance_policy_id", Type: "INT"},
				{Name: "claim_number", Type: "VARCHAR(30)", NotNull: true},
				{Name: "total_amount", Type: "NUMERIC(14,2)", NotNull: true},
				{Name: "allowed_amount", Type: "NUMERIC(14,2)"},
				{Name: "paid_amount", Type: "NUMERIC(14,2)"},
				{Name: "status", Type: "VARCHAR(20)", NotNull: true, Default: "'submitted'"},
				{Name: "submitted_at", Type: "TIMESTAMPTZ", NotNull: true},
				{Name: "adjudicated_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "insurance_policies", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "patient_id", Type: "INT", NotNull: true},
				{Name: "plan_name", Type: "VARCHAR(100)", NotNull: true},
				{Name: "plan_type", Type: "VARCHAR(30)", NotNull: true},
				{Name: "group_number", Type: "VARCHAR(30)"},
				{Name: "member_id", Type: "VARCHAR(30)", NotNull: true},
				{Name: "effective_date", Type: "DATE", NotNull: true},
				{Name: "termination_date", Type: "DATE"},
				{Name: "copay", Type: "NUMERIC(8,2)"},
				{Name: "deductible", Type: "NUMERIC(10,2)"},
				{Name: "is_active", Type: "BOOLEAN", NotNull: true, Default: "true"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			// --- RBAC tables (facility-scoped) ---
			{Name: "users", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "email", Type: "VARCHAR(255)", NotNull: true},
				{Name: "name", Type: "VARCHAR(200)", NotNull: true},
				{Name: "password_hash", Type: "VARCHAR(255)", NotNull: true},
				{Name: "facility", Type: "VARCHAR(100)"},
				{Name: "last_login_at", Type: "TIMESTAMPTZ"},
				{Name: "is_active", Type: "BOOLEAN", NotNull: true, Default: "true"},
				{Name: "mfa_enabled", Type: "BOOLEAN", NotNull: true, Default: "false"},
				{Name: "created_at", Type: "TIMESTAMPTZ", NotNull: true, Default: "now()"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "roles", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "name", Type: "VARCHAR(50)", NotNull: true},
				{Name: "description", Type: "TEXT"},
				{Name: "is_system_role", Type: "BOOLEAN", NotNull: true, Default: "false"},
				{Name: "created_at", Type: "TIMESTAMPTZ", NotNull: true, Default: "now()"},
			}},
			{Name: "permissions", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "name", Type: "VARCHAR(100)", NotNull: true},
				{Name: "resource_type", Type: "VARCHAR(50)", NotNull: true},
				{Name: "action", Type: "VARCHAR(20)", NotNull: true},
				{Name: "description", Type: "TEXT"},
			}},
			{Name: "role_permissions", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "role_id", Type: "INT", NotNull: true},
				{Name: "permission_id", Type: "INT", NotNull: true},
			}},
			{Name: "user_roles", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "user_id", Type: "INT", NotNull: true},
				{Name: "role_id", Type: "INT", NotNull: true},
				{Name: "granted_by", Type: "INT"},
				{Name: "granted_at", Type: "TIMESTAMPTZ", NotNull: true, Default: "now()"},
			}},
			// --- IoT medical device telemetry ---
			{Name: "medical_devices", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "device_type", Type: "VARCHAR(30)", NotNull: true},
				{Name: "model", Type: "VARCHAR(50)", NotNull: true},
				{Name: "serial_number", Type: "VARCHAR(50)", NotNull: true},
				{Name: "firmware_version", Type: "VARCHAR(20)"},
				{Name: "facility", Type: "VARCHAR(100)", NotNull: true},
				{Name: "assigned_patient_id", Type: "INT"},
				{Name: "installed_at", Type: "TIMESTAMPTZ", NotNull: true},
				{Name: "last_seen_at", Type: "TIMESTAMPTZ"},
				{Name: "is_active", Type: "BOOLEAN", NotNull: true, Default: "true"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
				{Name: "deleted_by", Type: "INT"},
			}},
			{Name: "device_readings", Columns: []ColumnDef{
				{Name: "id", Type: "BIGSERIAL", IsSerial: true},
				{Name: "device_id", Type: "INT", NotNull: true},
				{Name: "patient_id", Type: "INT"},
				{Name: "reading_type", Type: "VARCHAR(30)", NotNull: true},
				{Name: "value", Type: "NUMERIC(18,6)", NotNull: true},
				{Name: "unit", Type: "VARCHAR(20)", NotNull: true},
				{Name: "quality_score", Type: "SMALLINT"},
				{Name: "recorded_at", Type: "TIMESTAMPTZ", NotNull: true},
				{Name: "received_at", Type: "TIMESTAMPTZ", NotNull: true, Default: "now()"},
			}},
			{Name: "device_alerts", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "device_id", Type: "INT", NotNull: true},
				{Name: "patient_id", Type: "INT"},
				{Name: "alert_rule_id", Type: "INT", NotNull: true},
				{Name: "severity", Type: "VARCHAR(20)", NotNull: true},
				{Name: "message", Type: "TEXT", NotNull: true},
				{Name: "reading_value", Type: "NUMERIC(18,6)"},
				{Name: "threshold", Type: "NUMERIC(18,6)"},
				{Name: "triggered_at", Type: "TIMESTAMPTZ", NotNull: true},
				{Name: "acknowledged_by", Type: "INT"},
				{Name: "acknowledged_at", Type: "TIMESTAMPTZ"},
				{Name: "resolved_at", Type: "TIMESTAMPTZ"},
			}},
			{Name: "alert_rules", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "device_type", Type: "VARCHAR(30)", NotNull: true},
				{Name: "metric_name", Type: "VARCHAR(50)", NotNull: true},
				{Name: "condition_operator", Type: "VARCHAR(10)", NotNull: true},
				{Name: "threshold", Type: "NUMERIC(18,6)", NotNull: true},
				{Name: "severity", Type: "VARCHAR(20)", NotNull: true},
				{Name: "cooldown_minutes", Type: "INT", NotNull: true, Default: "60"},
				{Name: "is_active", Type: "BOOLEAN", NotNull: true, Default: "true"},
				{Name: "created_at", Type: "TIMESTAMPTZ", NotNull: true, Default: "now()"},
			}},
			// --- Medical supply chain tables ---
			{Name: "suppliers", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "name", Type: "VARCHAR(200)", NotNull: true},
				{Name: "contact_email", Type: "VARCHAR(255)"},
				{Name: "country", Type: "VARCHAR(50)", NotNull: true},
				{Name: "rating", Type: "NUMERIC(3,2)"},
				{Name: "payment_terms", Type: "VARCHAR(20)", NotNull: true, Default: "'net_30'"},
				{Name: "is_active", Type: "BOOLEAN", NotNull: true, Default: "true"},
				{Name: "metadata", Type: "JSONB"},
				{Name: "created_at", Type: "TIMESTAMPTZ", NotNull: true, Default: "now()"},
				{Name: "deleted_at", Type: "TIMESTAMPTZ"},
			}},
			{Name: "warehouses", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "name", Type: "VARCHAR(100)", NotNull: true},
				{Name: "location", Type: "VARCHAR(200)", NotNull: true},
				{Name: "capacity", Type: "INT", NotNull: true},
				{Name: "current_utilization", Type: "INT", NotNull: true, Default: "0"},
				{Name: "is_active", Type: "BOOLEAN", NotNull: true, Default: "true"},
			}},
			{Name: "supply_orders", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "supplier_id", Type: "INT", NotNull: true},
				{Name: "order_number", Type: "VARCHAR(30)", NotNull: true},
				{Name: "status", Type: "VARCHAR(20)", NotNull: true, Default: "'pending'"},
				{Name: "total_amount", Type: "NUMERIC(12,2)", NotNull: true},
				{Name: "order_date", Type: "DATE", NotNull: true},
				{Name: "expected_delivery", Type: "DATE"},
				{Name: "notes", Type: "TEXT"},
				{Name: "created_at", Type: "TIMESTAMPTZ", NotNull: true, Default: "now()"},
			}},
			{Name: "supply_order_lines", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "order_id", Type: "INT", NotNull: true},
				{Name: "sku", Type: "VARCHAR(50)", NotNull: true},
				{Name: "description", Type: "VARCHAR(200)", NotNull: true},
				{Name: "quantity", Type: "INT", NotNull: true},
				{Name: "unit_cost", Type: "NUMERIC(10,2)", NotNull: true},
			}},
			{Name: "supply_shipments", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "order_id", Type: "INT", NotNull: true},
				{Name: "destination_warehouse_id", Type: "INT", NotNull: true},
				{Name: "tracking_number", Type: "VARCHAR(50)"},
				{Name: "status", Type: "VARCHAR(20)", NotNull: true, Default: "'in_transit'"},
				{Name: "shipped_date", Type: "DATE"},
				{Name: "delivered_date", Type: "DATE"},
				{Name: "requires_cold_chain", Type: "BOOLEAN", NotNull: true, Default: "false"},
			}},
			{Name: "shipment_events", Columns: []ColumnDef{
				{Name: "id", Type: "BIGSERIAL", IsSerial: true},
				{Name: "shipment_id", Type: "INT", NotNull: true},
				{Name: "event_type", Type: "VARCHAR(30)", NotNull: true},
				{Name: "location", Type: "VARCHAR(200)"},
				{Name: "temperature_celsius", Type: "NUMERIC(5,2)"},
				{Name: "notes", Type: "TEXT"},
				{Name: "recorded_at", Type: "TIMESTAMPTZ", NotNull: true},
			}},
			{Name: "inventory_transfers", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "source_warehouse_id", Type: "INT", NotNull: true},
				{Name: "destination_warehouse_id", Type: "INT", NotNull: true},
				{Name: "sku", Type: "VARCHAR(50)", NotNull: true},
				{Name: "quantity", Type: "INT", NotNull: true},
				{Name: "status", Type: "VARCHAR(20)", NotNull: true, Default: "'pending'"},
				{Name: "requested_at", Type: "TIMESTAMPTZ", NotNull: true, Default: "now()"},
				{Name: "completed_at", Type: "TIMESTAMPTZ"},
			}},
			{Name: "stock_levels", Columns: []ColumnDef{
				{Name: "id", Type: "SERIAL", IsSerial: true},
				{Name: "warehouse_id", Type: "INT", NotNull: true},
				{Name: "sku", Type: "VARCHAR(50)", NotNull: true},
				{Name: "quantity_on_hand", Type: "INT", NotNull: true, Default: "0"},
				{Name: "reorder_point", Type: "INT", NotNull: true, Default: "10"},
				{Name: "last_counted_at", Type: "TIMESTAMPTZ"},
			}},
		},
		Indexes: []IndexDef{
			// Clinical indexes
			{Name: "idx_hc_pat_mrn", Table: "patients", Columns: []string{"mrn"}, Unique: true},
			{Name: "idx_hc_pat_dob", Table: "patients", Columns: []string{"date_of_birth"}},
			{Name: "idx_hc_pat_deleted", Table: "patients", Columns: []string{"deleted_at"}},
			{Name: "idx_hc_prov_npi", Table: "providers", Columns: []string{"npi"}, Unique: true},
			{Name: "idx_hc_prov_user", Table: "providers", Columns: []string{"user_id"}},
			{Name: "idx_hc_prov_spec", Table: "providers", Columns: []string{"specialty"}},
			{Name: "idx_hc_prov_deleted", Table: "providers", Columns: []string{"deleted_at"}},
			{Name: "idx_hc_enc_patient", Table: "encounters", Columns: []string{"patient_id"}},
			{Name: "idx_hc_enc_provider", Table: "encounters", Columns: []string{"provider_id"}},
			{Name: "idx_hc_enc_admit", Table: "encounters", Columns: []string{"admission_date"}},
			{Name: "idx_hc_enc_status", Table: "encounters", Columns: []string{"status"}},
			{Name: "idx_hc_enc_type", Table: "encounters", Columns: []string{"encounter_type"}},
			{Name: "idx_hc_enc_deleted", Table: "encounters", Columns: []string{"deleted_at"}},
			{Name: "idx_hc_diag_enc", Table: "diagnoses", Columns: []string{"encounter_id"}},
			{Name: "idx_hc_diag_icd", Table: "diagnoses", Columns: []string{"icd_code"}},
			{Name: "idx_hc_diag_by", Table: "diagnoses", Columns: []string{"diagnosed_by"}},
			{Name: "idx_hc_proc_enc", Table: "procedures", Columns: []string{"encounter_id"}},
			{Name: "idx_hc_proc_cpt", Table: "procedures", Columns: []string{"cpt_code"}},
			{Name: "idx_hc_proc_by", Table: "procedures", Columns: []string{"performed_by"}},
			{Name: "idx_hc_proc_at", Table: "procedures", Columns: []string{"performed_at"}},
			{Name: "idx_hc_med_ndc", Table: "medications", Columns: []string{"ndc_code"}, Unique: true},
			{Name: "idx_hc_med_class", Table: "medications", Columns: []string{"drug_class"}},
			{Name: "idx_hc_rx_enc", Table: "prescriptions", Columns: []string{"encounter_id"}},
			{Name: "idx_hc_rx_med", Table: "prescriptions", Columns: []string{"medication_id"}},
			{Name: "idx_hc_rx_patient", Table: "prescriptions", Columns: []string{"patient_id"}},
			{Name: "idx_hc_rx_by", Table: "prescriptions", Columns: []string{"prescribed_by"}},
			{Name: "idx_hc_rx_status", Table: "prescriptions", Columns: []string{"status"}},
			{Name: "idx_hc_allergy_patient", Table: "allergies", Columns: []string{"patient_id"}},
			{Name: "idx_hc_allergy_type", Table: "allergies", Columns: []string{"allergy_type"}},
			{Name: "idx_hc_vit_enc", Table: "vitals", Columns: []string{"encounter_id"}},
			{Name: "idx_hc_vit_patient", Table: "vitals", Columns: []string{"patient_id"}},
			{Name: "idx_hc_vit_recorded", Table: "vitals", Columns: []string{"recorded_at"}},
			{Name: "idx_hc_vit_patient_time", Table: "vitals", Columns: []string{"patient_id", "recorded_at"}},
			{Name: "idx_hc_lab_enc", Table: "lab_results", Columns: []string{"encounter_id"}},
			{Name: "idx_hc_lab_patient", Table: "lab_results", Columns: []string{"patient_id"}},
			{Name: "idx_hc_lab_by", Table: "lab_results", Columns: []string{"ordered_by"}},
			{Name: "idx_hc_lab_test", Table: "lab_results", Columns: []string{"test_name"}},
			{Name: "idx_hc_lab_collected", Table: "lab_results", Columns: []string{"collected_at"}},
			{Name: "idx_hc_imm_patient", Table: "immunizations", Columns: []string{"patient_id"}},
			{Name: "idx_hc_imm_vaccine", Table: "immunizations", Columns: []string{"vaccine_code"}},
			{Name: "idx_hc_ref_enc", Table: "referrals", Columns: []string{"encounter_id"}},
			{Name: "idx_hc_ref_patient", Table: "referrals", Columns: []string{"patient_id"}},
			{Name: "idx_hc_ref_from", Table: "referrals", Columns: []string{"referring_provider_id"}},
			{Name: "idx_hc_ref_to", Table: "referrals", Columns: []string{"referred_to_provider_id"}},
			{Name: "idx_hc_ref_status", Table: "referrals", Columns: []string{"status"}},
			{Name: "idx_hc_cp_patient", Table: "care_plans", Columns: []string{"patient_id"}},
			{Name: "idx_hc_cp_provider", Table: "care_plans", Columns: []string{"provider_id"}},
			{Name: "idx_hc_cp_status", Table: "care_plans", Columns: []string{"status"}},
			{Name: "idx_hc_mh_patient", Table: "medical_history", Columns: []string{"patient_id"}},
			{Name: "idx_hc_mh_type", Table: "medical_history", Columns: []string{"history_type"}},
			{Name: "idx_hc_bill_enc", Table: "billing_claims", Columns: []string{"encounter_id"}},
			{Name: "idx_hc_bill_patient", Table: "billing_claims", Columns: []string{"patient_id"}},
			{Name: "idx_hc_bill_ins", Table: "billing_claims", Columns: []string{"insurance_policy_id"}},
			{Name: "idx_hc_bill_claim", Table: "billing_claims", Columns: []string{"claim_number"}, Unique: true},
			{Name: "idx_hc_bill_status", Table: "billing_claims", Columns: []string{"status"}},
			{Name: "idx_hc_bill_submitted", Table: "billing_claims", Columns: []string{"submitted_at"}},
			{Name: "idx_hc_ins_patient", Table: "insurance_policies", Columns: []string{"patient_id"}},
			{Name: "idx_hc_ins_eff", Table: "insurance_policies", Columns: []string{"effective_date"}},
			// RBAC indexes
			{Name: "idx_hc_usr_email", Table: "users", Columns: []string{"email"}, Unique: true},
			{Name: "idx_hc_usr_facility", Table: "users", Columns: []string{"facility"}},
			{Name: "idx_hc_usr_active", Table: "users", Columns: []string{"is_active"}},
			{Name: "idx_hc_usr_deleted", Table: "users", Columns: []string{"deleted_at"}},
			{Name: "idx_hc_role_name", Table: "roles", Columns: []string{"name"}, Unique: true},
			{Name: "idx_hc_perm_name", Table: "permissions", Columns: []string{"name"}, Unique: true},
			{Name: "idx_hc_perm_res", Table: "permissions", Columns: []string{"resource_type", "action"}},
			{Name: "idx_hc_rp_role", Table: "role_permissions", Columns: []string{"role_id"}},
			{Name: "idx_hc_rp_perm", Table: "role_permissions", Columns: []string{"permission_id"}},
			{Name: "idx_hc_rp_uniq", Table: "role_permissions", Columns: []string{"role_id", "permission_id"}, Unique: true},
			{Name: "idx_hc_ur_user", Table: "user_roles", Columns: []string{"user_id"}},
			{Name: "idx_hc_ur_role", Table: "user_roles", Columns: []string{"role_id"}},
			{Name: "idx_hc_ur_uniq", Table: "user_roles", Columns: []string{"user_id", "role_id"}, Unique: true},
			// IoT indexes
			{Name: "idx_hc_dev_type", Table: "medical_devices", Columns: []string{"device_type"}},
			{Name: "idx_hc_dev_serial", Table: "medical_devices", Columns: []string{"serial_number"}, Unique: true},
			{Name: "idx_hc_dev_patient", Table: "medical_devices", Columns: []string{"assigned_patient_id"}},
			{Name: "idx_hc_dev_facility", Table: "medical_devices", Columns: []string{"facility"}},
			{Name: "idx_hc_dr_device", Table: "device_readings", Columns: []string{"device_id"}},
			{Name: "idx_hc_dr_patient", Table: "device_readings", Columns: []string{"patient_id"}},
			{Name: "idx_hc_dr_type", Table: "device_readings", Columns: []string{"reading_type"}},
			{Name: "idx_hc_dr_recorded", Table: "device_readings", Columns: []string{"recorded_at"}},
			{Name: "idx_hc_dr_device_time", Table: "device_readings", Columns: []string{"device_id", "recorded_at"}},
			{Name: "idx_hc_da_device", Table: "device_alerts", Columns: []string{"device_id"}},
			{Name: "idx_hc_da_patient", Table: "device_alerts", Columns: []string{"patient_id"}},
			{Name: "idx_hc_da_rule", Table: "device_alerts", Columns: []string{"alert_rule_id"}},
			{Name: "idx_hc_da_severity", Table: "device_alerts", Columns: []string{"severity"}},
			{Name: "idx_hc_da_triggered", Table: "device_alerts", Columns: []string{"triggered_at"}},
			{Name: "idx_hc_arule_type", Table: "alert_rules", Columns: []string{"device_type"}},
			// Supply chain indexes
			{Name: "idx_hc_sup_country", Table: "suppliers", Columns: []string{"country"}},
			{Name: "idx_hc_sup_active", Table: "suppliers", Columns: []string{"is_active"}},
			{Name: "idx_hc_wh_location", Table: "warehouses", Columns: []string{"location"}},
			{Name: "idx_hc_so_supplier", Table: "supply_orders", Columns: []string{"supplier_id"}},
			{Name: "idx_hc_so_number", Table: "supply_orders", Columns: []string{"order_number"}, Unique: true},
			{Name: "idx_hc_so_status", Table: "supply_orders", Columns: []string{"status"}},
			{Name: "idx_hc_so_date", Table: "supply_orders", Columns: []string{"order_date"}},
			{Name: "idx_hc_sol_order", Table: "supply_order_lines", Columns: []string{"order_id"}},
			{Name: "idx_hc_sol_sku", Table: "supply_order_lines", Columns: []string{"sku"}},
			{Name: "idx_hc_ss_order", Table: "supply_shipments", Columns: []string{"order_id"}},
			{Name: "idx_hc_ss_wh", Table: "supply_shipments", Columns: []string{"destination_warehouse_id"}},
			{Name: "idx_hc_ss_track", Table: "supply_shipments", Columns: []string{"tracking_number"}},
			{Name: "idx_hc_ss_status", Table: "supply_shipments", Columns: []string{"status"}},
			{Name: "idx_hc_se_ship", Table: "shipment_events", Columns: []string{"shipment_id"}},
			{Name: "idx_hc_se_type", Table: "shipment_events", Columns: []string{"event_type"}},
			{Name: "idx_hc_se_time", Table: "shipment_events", Columns: []string{"recorded_at"}},
			{Name: "idx_hc_it_src", Table: "inventory_transfers", Columns: []string{"source_warehouse_id"}},
			{Name: "idx_hc_it_dst", Table: "inventory_transfers", Columns: []string{"destination_warehouse_id"}},
			{Name: "idx_hc_it_sku", Table: "inventory_transfers", Columns: []string{"sku"}},
			{Name: "idx_hc_sl_wh", Table: "stock_levels", Columns: []string{"warehouse_id"}},
			{Name: "idx_hc_sl_sku", Table: "stock_levels", Columns: []string{"sku"}},
			{Name: "idx_hc_sl_wh_sku", Table: "stock_levels", Columns: []string{"warehouse_id", "sku"}, Unique: true},
		},
		ForeignKeys: []FKDef{
			// Clinical FKs
			{Name: "fk_hc_pat_created", Table: "patients", Column: "created_by", RefTable: "users", RefColumn: "id"},
			{Name: "fk_hc_prov_user", Table: "providers", Column: "user_id", RefTable: "users", RefColumn: "id"},
			{Name: "fk_hc_enc_patient", Table: "encounters", Column: "patient_id", RefTable: "patients", RefColumn: "id"},
			{Name: "fk_hc_enc_provider", Table: "encounters", Column: "provider_id", RefTable: "providers", RefColumn: "id"},
			{Name: "fk_hc_enc_created", Table: "encounters", Column: "created_by", RefTable: "users", RefColumn: "id"},
			{Name: "fk_hc_diag_enc", Table: "diagnoses", Column: "encounter_id", RefTable: "encounters", RefColumn: "id"},
			{Name: "fk_hc_diag_by", Table: "diagnoses", Column: "diagnosed_by", RefTable: "providers", RefColumn: "id"},
			{Name: "fk_hc_proc_enc", Table: "procedures", Column: "encounter_id", RefTable: "encounters", RefColumn: "id"},
			{Name: "fk_hc_proc_by", Table: "procedures", Column: "performed_by", RefTable: "providers", RefColumn: "id"},
			{Name: "fk_hc_rx_enc", Table: "prescriptions", Column: "encounter_id", RefTable: "encounters", RefColumn: "id"},
			{Name: "fk_hc_rx_med", Table: "prescriptions", Column: "medication_id", RefTable: "medications", RefColumn: "id"},
			{Name: "fk_hc_rx_patient", Table: "prescriptions", Column: "patient_id", RefTable: "patients", RefColumn: "id"},
			{Name: "fk_hc_rx_by", Table: "prescriptions", Column: "prescribed_by", RefTable: "providers", RefColumn: "id"},
			{Name: "fk_hc_allergy_patient", Table: "allergies", Column: "patient_id", RefTable: "patients", RefColumn: "id"},
			{Name: "fk_hc_allergy_verified", Table: "allergies", Column: "verified_by", RefTable: "providers", RefColumn: "id"},
			{Name: "fk_hc_vit_enc", Table: "vitals", Column: "encounter_id", RefTable: "encounters", RefColumn: "id"},
			{Name: "fk_hc_vit_patient", Table: "vitals", Column: "patient_id", RefTable: "patients", RefColumn: "id"},
			{Name: "fk_hc_vit_by", Table: "vitals", Column: "recorded_by", RefTable: "providers", RefColumn: "id"},
			{Name: "fk_hc_lab_enc", Table: "lab_results", Column: "encounter_id", RefTable: "encounters", RefColumn: "id"},
			{Name: "fk_hc_lab_patient", Table: "lab_results", Column: "patient_id", RefTable: "patients", RefColumn: "id"},
			{Name: "fk_hc_lab_by", Table: "lab_results", Column: "ordered_by", RefTable: "providers", RefColumn: "id"},
			{Name: "fk_hc_imm_patient", Table: "immunizations", Column: "patient_id", RefTable: "patients", RefColumn: "id"},
			{Name: "fk_hc_imm_by", Table: "immunizations", Column: "administered_by", RefTable: "providers", RefColumn: "id"},
			{Name: "fk_hc_ref_enc", Table: "referrals", Column: "encounter_id", RefTable: "encounters", RefColumn: "id"},
			{Name: "fk_hc_ref_patient", Table: "referrals", Column: "patient_id", RefTable: "patients", RefColumn: "id"},
			{Name: "fk_hc_ref_from", Table: "referrals", Column: "referring_provider_id", RefTable: "providers", RefColumn: "id"},
			{Name: "fk_hc_ref_to", Table: "referrals", Column: "referred_to_provider_id", RefTable: "providers", RefColumn: "id"},
			{Name: "fk_hc_cp_patient", Table: "care_plans", Column: "patient_id", RefTable: "patients", RefColumn: "id"},
			{Name: "fk_hc_cp_provider", Table: "care_plans", Column: "provider_id", RefTable: "providers", RefColumn: "id"},
			{Name: "fk_hc_mh_patient", Table: "medical_history", Column: "patient_id", RefTable: "patients", RefColumn: "id"},
			{Name: "fk_hc_mh_by", Table: "medical_history", Column: "recorded_by", RefTable: "providers", RefColumn: "id"},
			{Name: "fk_hc_bill_enc", Table: "billing_claims", Column: "encounter_id", RefTable: "encounters", RefColumn: "id"},
			{Name: "fk_hc_bill_patient", Table: "billing_claims", Column: "patient_id", RefTable: "patients", RefColumn: "id"},
			{Name: "fk_hc_bill_ins", Table: "billing_claims", Column: "insurance_policy_id", RefTable: "insurance_policies", RefColumn: "id"},
			{Name: "fk_hc_ins_patient", Table: "insurance_policies", Column: "patient_id", RefTable: "patients", RefColumn: "id"},
			// RBAC FKs
			{Name: "fk_hc_rp_role", Table: "role_permissions", Column: "role_id", RefTable: "roles", RefColumn: "id"},
			{Name: "fk_hc_rp_perm", Table: "role_permissions", Column: "permission_id", RefTable: "permissions", RefColumn: "id"},
			{Name: "fk_hc_ur_user", Table: "user_roles", Column: "user_id", RefTable: "users", RefColumn: "id"},
			{Name: "fk_hc_ur_role", Table: "user_roles", Column: "role_id", RefTable: "roles", RefColumn: "id"},
			{Name: "fk_hc_ur_granted", Table: "user_roles", Column: "granted_by", RefTable: "users", RefColumn: "id"},
			// IoT FKs
			{Name: "fk_hc_dev_patient", Table: "medical_devices", Column: "assigned_patient_id", RefTable: "patients", RefColumn: "id"},
			{Name: "fk_hc_dr_device", Table: "device_readings", Column: "device_id", RefTable: "medical_devices", RefColumn: "id"},
			{Name: "fk_hc_dr_patient", Table: "device_readings", Column: "patient_id", RefTable: "patients", RefColumn: "id"},
			{Name: "fk_hc_da_device", Table: "device_alerts", Column: "device_id", RefTable: "medical_devices", RefColumn: "id"},
			{Name: "fk_hc_da_patient", Table: "device_alerts", Column: "patient_id", RefTable: "patients", RefColumn: "id"},
			{Name: "fk_hc_da_rule", Table: "device_alerts", Column: "alert_rule_id", RefTable: "alert_rules", RefColumn: "id"},
			{Name: "fk_hc_da_ack", Table: "device_alerts", Column: "acknowledged_by", RefTable: "users", RefColumn: "id"},
			// Supply chain FKs (medical supply logistics)
			{Name: "fk_hc_po_supplier", Table: "supply_orders", Column: "supplier_id", RefTable: "suppliers", RefColumn: "id"},
			{Name: "fk_hc_pol_po", Table: "supply_order_lines", Column: "order_id", RefTable: "supply_orders", RefColumn: "id"},
			{Name: "fk_hc_ship_order", Table: "supply_shipments", Column: "order_id", RefTable: "supply_orders", RefColumn: "id"},
			{Name: "fk_hc_ship_wh", Table: "supply_shipments", Column: "destination_warehouse_id", RefTable: "warehouses", RefColumn: "id"},
			{Name: "fk_hc_te_ship", Table: "shipment_events", Column: "shipment_id", RefTable: "supply_shipments", RefColumn: "id"},
			{Name: "fk_hc_it_src", Table: "inventory_transfers", Column: "source_warehouse_id", RefTable: "warehouses", RefColumn: "id"},
			{Name: "fk_hc_it_dst", Table: "inventory_transfers", Column: "destination_warehouse_id", RefTable: "warehouses", RefColumn: "id"},
			{Name: "fk_hc_stock_wh", Table: "stock_levels", Column: "warehouse_id", RefTable: "warehouses", RefColumn: "id"},
		},
	}
}


